// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agent} from '../models';
import {agentruntime} from '../models';

export function ActivateSkillVersion(arg1:string,arg2:string):Promise<void>;

export function AgentEnabled(arg1:string):Promise<boolean>;

export function AgentInventory():Promise<desktop.AgentInventoryDTO>;

export function AgentSkillDocument(arg1:string):Promise<string>;

export function CreateSkillVersion(arg1:desktop.CreateSkillVersionRequest):Promise<agent.SkillVersion>;

export function GetAgentRunTrace(arg1:string,arg2:string):Promise<agentruntime.RunTrace>;

export function ListAgentRuns(arg1:string):Promise<Array<agentruntime.RunSummary>>;

export function ListSkillVersions(arg1:string):Promise<Array<agent.SkillVersion>>;

export function RunStatusCounts(arg1:string):Promise<Record<string, number>>;

export function SetAgentEnabled(arg1:string,arg2:boolean):Promise<void>;
