// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentInventory() {
  return window['go']['desktop']['AgentBinding']['AgentInventory']();
}

export function GetAgentRunTrace(arg1, arg2) {
  return window['go']['desktop']['AgentBinding']['GetAgentRunTrace'](arg1, arg2);
}

export function ListAgentRuns(arg1) {
  return window['go']['desktop']['AgentBinding']['ListAgentRuns'](arg1);
}

export function RunStatusCounts(arg1) {
  return window['go']['desktop']['AgentBinding']['RunStatusCounts'](arg1);
}
