// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {agentruntime} from '../models';

export function AgentInventory():Promise<desktop.AgentInventoryDTO>;

export function GetAgentRunTrace(arg1:string,arg2:string):Promise<agentruntime.RunTrace>;

export function ListAgentRuns(arg1:string):Promise<Array<agentruntime.RunSummary>>;

export function RunStatusCounts(arg1:string):Promise<Record<string, number>>;
