// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AddRelation(arg1:desktop.AddRelationRequest):Promise<desktop.AssetRelationDTO>;

export function AddUsage(arg1:desktop.AddUsageRequest):Promise<desktop.AssetUsageDTO>;

export function AddVersion(arg1:desktop.AddVersionRequest):Promise<desktop.AssetVersionDTO>;

export function ApproveVersion(arg1:desktop.ApproveVersionRequest):Promise<desktop.AssetVersionDTO>;

export function AttachFile(arg1:desktop.AttachFileRequest):Promise<desktop.AssetFileDTO>;

export function AttachJobResult(arg1:desktop.AttachJobResultRequest):Promise<desktop.AssetVersionDTO>;

export function CreateAsset(arg1:desktop.CreateAssetRequest):Promise<desktop.AssetDTO>;

export function GetApprovalImpact(arg1:string):Promise<desktop.ApprovalImpactDTO>;

export function GetAsset(arg1:string):Promise<desktop.AssetDTO>;

export function ListAssets(arg1:desktop.ListAssetsRequest):Promise<Array<desktop.AssetDTO>>;

export function ListFiles(arg1:string):Promise<Array<desktop.AssetFileDTO>>;

export function ListLineage(arg1:string):Promise<desktop.LineageDTO>;

export function ListUsages(arg1:string):Promise<Array<desktop.AssetUsageDTO>>;

export function ListUsagesOfConsumer(arg1:string,arg2:string):Promise<Array<desktop.AssetUsageDTO>>;

export function ListVersions(arg1:string):Promise<Array<desktop.AssetVersionDTO>>;

export function SetAssetLicense(arg1:desktop.SetAssetLicenseRequest):Promise<void>;

export function SetUsageParams(arg1:desktop.SetUsageParamsRequest):Promise<void>;
