// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRelation(arg1) {
  return window['go']['desktop']['AssetsBinding']['AddRelation'](arg1);
}

export function AddUsage(arg1) {
  return window['go']['desktop']['AssetsBinding']['AddUsage'](arg1);
}

export function AddVersion(arg1) {
  return window['go']['desktop']['AssetsBinding']['AddVersion'](arg1);
}

export function ApproveVersion(arg1) {
  return window['go']['desktop']['AssetsBinding']['ApproveVersion'](arg1);
}

export function AttachFile(arg1) {
  return window['go']['desktop']['AssetsBinding']['AttachFile'](arg1);
}

export function AttachJobResult(arg1) {
  return window['go']['desktop']['AssetsBinding']['AttachJobResult'](arg1);
}

export function CreateAsset(arg1) {
  return window['go']['desktop']['AssetsBinding']['CreateAsset'](arg1);
}

export function GetApprovalImpact(arg1) {
  return window['go']['desktop']['AssetsBinding']['GetApprovalImpact'](arg1);
}

export function GetAsset(arg1) {
  return window['go']['desktop']['AssetsBinding']['GetAsset'](arg1);
}

export function ListAssets(arg1) {
  return window['go']['desktop']['AssetsBinding']['ListAssets'](arg1);
}

export function ListFiles(arg1) {
  return window['go']['desktop']['AssetsBinding']['ListFiles'](arg1);
}

export function ListLineage(arg1) {
  return window['go']['desktop']['AssetsBinding']['ListLineage'](arg1);
}

export function ListUsages(arg1) {
  return window['go']['desktop']['AssetsBinding']['ListUsages'](arg1);
}

export function ListVersions(arg1) {
  return window['go']['desktop']['AssetsBinding']['ListVersions'](arg1);
}
