// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AddVersion(arg1:desktop.AddVersionRequest):Promise<desktop.AssetVersionDTO>;

export function ApproveVersion(arg1:desktop.ApproveVersionRequest):Promise<desktop.AssetVersionDTO>;

export function AttachFile(arg1:desktop.AttachFileRequest):Promise<desktop.AssetFileDTO>;

export function CreateAsset(arg1:desktop.CreateAssetRequest):Promise<desktop.AssetDTO>;

export function GetAsset(arg1:string):Promise<desktop.AssetDTO>;

export function ListAssets(arg1:desktop.ListAssetsRequest):Promise<Array<desktop.AssetDTO>>;

export function ListFiles(arg1:string):Promise<Array<desktop.AssetFileDTO>>;

export function ListVersions(arg1:string):Promise<Array<desktop.AssetVersionDTO>>;
