// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBackup() {
  return window['go']['desktop']['BackupBinding']['ExportBackup']();
}

export function PreviewBackup(arg1) {
  return window['go']['desktop']['BackupBinding']['PreviewBackup'](arg1);
}
