// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ExportBackup():Promise<string>;

export function PreviewBackup(arg1:string):Promise<desktop.BackupPreview>;
