// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupStateHeld() {
  return window['go']['desktop']['BackupBinding']['BackupStateHeld']();
}

export function CancelGarbageCollection() {
  return window['go']['desktop']['BackupBinding']['CancelGarbageCollection']();
}

export function DiscardBackupState() {
  return window['go']['desktop']['BackupBinding']['DiscardBackupState']();
}

export function ExportBackup() {
  return window['go']['desktop']['BackupBinding']['ExportBackup']();
}

export function PreviewBackup(arg1) {
  return window['go']['desktop']['BackupBinding']['PreviewBackup'](arg1);
}

export function PreviewGarbageListing() {
  return window['go']['desktop']['BackupBinding']['PreviewGarbageListing']();
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['desktop']['BackupBinding']['RestoreBackup'](arg1, arg2);
}

export function RunGarbageCollection(arg1) {
  return window['go']['desktop']['BackupBinding']['RunGarbageCollection'](arg1);
}
