// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CollectDiagnostics(arg1:Array<string>):Promise<desktop.DiagnosticsBundleDTO>;

export function PlanDiagnostics(arg1:Array<string>):Promise<desktop.DiagnosticsPlanDTO>;
