// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CollectDiagnostics(arg1) {
  return window['go']['desktop']['DiagnosticsBinding']['CollectDiagnostics'](arg1);
}

export function PlanDiagnostics(arg1) {
  return window['go']['desktop']['DiagnosticsBinding']['PlanDiagnostics'](arg1);
}
