// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AcceptStoryEntity(arg1:desktop.DecideStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function AcceptStoryEvent(arg1:desktop.DecideStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function AddSourceDocumentVersion(arg1:desktop.AddSourceDocumentVersionRequest):Promise<desktop.SourceDocumentVersionDTO>;

export function ApprovePanelImage(arg1:desktop.ApprovePanelImageRequest):Promise<desktop.StoryboardPanelVersionDTO>;

export function ApproveScriptVersion(arg1:desktop.ApproveScriptVersionRequest):Promise<desktop.ScriptVersionDTO>;

export function ClearStaleMark(arg1:desktop.ClearStaleMarkRequest):Promise<boolean>;

export function CreateChapter(arg1:desktop.CreateChapterRequest):Promise<desktop.ChapterDTO>;

export function CreateDirectorPlanVersion(arg1:desktop.CreateDirectorPlanVersionRequest):Promise<desktop.DirectorPlanVersionDTO>;

export function CreateEpisode(arg1:desktop.CreateEpisodeRequest):Promise<desktop.EpisodeDTO>;

export function CreatePanelVersion(arg1:desktop.CreatePanelVersionRequest):Promise<desktop.StoryboardPanelVersionDTO>;

export function CreateScene(arg1:desktop.CreateSceneRequest):Promise<desktop.SceneDTO>;

export function CreateScriptVersion(arg1:desktop.CreateScriptVersionRequest):Promise<desktop.ScriptVersionDTO>;

export function CreateShot(arg1:desktop.CreateShotRequest):Promise<desktop.ShotDTO>;

export function CreateSourceDocument(arg1:desktop.CreateSourceDocumentRequest):Promise<desktop.SourceDocumentDTO>;

export function CreateStageRun(arg1:desktop.CreateStageRunRequest):Promise<desktop.StageRunDTO>;

export function CreateStoryEntity(arg1:desktop.CreateStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function CreateStoryEvent(arg1:desktop.CreateStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function CreateStoryRelation(arg1:desktop.CreateStoryRelationRequest):Promise<desktop.StoryRelationDTO>;

export function CreateStoryboardItem(arg1:desktop.CreateStoryboardItemRequest):Promise<desktop.StoryboardItemDTO>;

export function CreateStoryboardVersion(arg1:desktop.CreateStoryboardVersionRequest):Promise<desktop.StoryboardVersionDTO>;

export function CreateWorkflowRun(arg1:desktop.CreateWorkflowRunRequest):Promise<desktop.WorkflowRunDTO>;

export function EnsureScript(arg1:string):Promise<desktop.ScriptDTO>;

export function EnsureStoryboard(arg1:string):Promise<desktop.StoryboardDTO>;

export function GetReviewReport(arg1:string):Promise<desktop.ReviewReportDTO>;

export function ListChapters(arg1:string):Promise<Array<desktop.ChapterDTO>>;

export function ListEpisodes(arg1:string):Promise<Array<desktop.EpisodeDTO>>;

export function ListOpenStaleMarks(arg1:string):Promise<Array<desktop.StaleMarkDTO>>;

export function ListPanels(arg1:string):Promise<Array<desktop.StoryboardPanelVersionDTO>>;

export function ListScenes(arg1:string):Promise<Array<desktop.SceneDTO>>;

export function ListShots(arg1:string):Promise<Array<desktop.ShotDTO>>;

export function ListSourceDocuments(arg1:string):Promise<Array<desktop.SourceDocumentDTO>>;

export function ListStageRuns(arg1:string):Promise<Array<desktop.StageRunDTO>>;

export function ListStaleMarks(arg1:string):Promise<Array<desktop.StaleMarkDTO>>;

export function ListStoryboardItems(arg1:string):Promise<Array<desktop.StoryboardItemDTO>>;

export function ListWorkflowEvents(arg1:string):Promise<Array<desktop.WorkflowEventDTO>>;

export function ListWorkflowRuns(arg1:string):Promise<Array<desktop.WorkflowRunDTO>>;

export function MarkStale(arg1:desktop.MarkStaleRequest):Promise<desktop.StaleMarkDTO>;

export function RecordReview(arg1:desktop.RecordReviewRequest):Promise<desktop.ReviewReportDTO>;

export function RejectStoryEntity(arg1:desktop.DecideStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function RejectStoryEvent(arg1:desktop.DecideStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function ReviseChapter(arg1:desktop.ReviseChapterRequest):Promise<desktop.ChapterDTO>;

export function SubmitGateDecision(arg1:desktop.SubmitGateDecisionRequest):Promise<desktop.UserGateDecisionDTO>;

export function TransitionStageRun(arg1:desktop.TransitionStageRunRequest):Promise<desktop.StageRunDTO>;

export function TransitionWorkflowRun(arg1:desktop.TransitionWorkflowRunRequest):Promise<desktop.WorkflowRunDTO>;

export function UpdateEpisodeStatus(arg1:desktop.UpdateEpisodeStatusRequest):Promise<desktop.EpisodeDTO>;

export function WaiveStaleMark(arg1:desktop.WaiveStaleMarkRequest):Promise<boolean>;
