// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AcceptStoryEntity(arg1:desktop.DecideStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function AcceptStoryEvent(arg1:desktop.DecideStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function AddSourceDocumentVersion(arg1:desktop.AddSourceDocumentVersionRequest):Promise<desktop.SourceDocumentVersionDTO>;

export function ApplyScriptGate(arg1:desktop.ApplyScriptGateRequest):Promise<desktop.StageRunDTO>;

export function ApproveAdaptationStrategyVersion(arg1:string):Promise<desktop.AdaptationStrategyVersionDTO>;

export function ApproveCandidate(arg1:desktop.ApproveCandidateRequest):Promise<desktop.StoryboardPanelVersionDTO>;

export function ApproveDirectorPlanVersion(arg1:desktop.ApproveDirectorPlanVersionRequest):Promise<desktop.DirectorPlanVersionDTO>;

export function ApprovePanelImage(arg1:desktop.ApprovePanelImageRequest):Promise<desktop.StoryboardPanelVersionDTO>;

export function ApproveScriptVersion(arg1:desktop.ApproveScriptVersionRequest):Promise<desktop.ScriptVersionDTO>;

export function ApproveStorySkeletonVersion(arg1:string):Promise<desktop.StorySkeletonVersionDTO>;

export function ApproveStoryboardVersion(arg1:desktop.ApproveStoryboardVersionRequest):Promise<desktop.StoryboardVersionDTO>;

export function ApprovedStoryboardVersionID(arg1:string):Promise<string>;

export function CheckStoryboardGate(arg1:desktop.CheckStoryboardGateRequest):Promise<void>;

export function ClearStaleMark(arg1:desktop.ClearStaleMarkRequest):Promise<boolean>;

export function CollectBatchResults(arg1:desktop.CollectBatchResultsRequest):Promise<Array<desktop.CollectedCandidateDTO>>;

export function CountDomainEvents(arg1:desktop.ListDomainEventsRequest):Promise<number>;

export function CreateAdaptationStrategyVersion(arg1:desktop.CreateAdaptationStrategyVersionRequest):Promise<desktop.AdaptationStrategyVersionDTO>;

export function CreateChapter(arg1:desktop.CreateChapterRequest):Promise<desktop.ChapterDTO>;

export function CreateDirectorPlanVersion(arg1:desktop.CreateDirectorPlanVersionRequest):Promise<desktop.DirectorPlanVersionDTO>;

export function CreateEpisode(arg1:desktop.CreateEpisodeRequest):Promise<desktop.EpisodeDTO>;

export function CreatePanelVersion(arg1:desktop.CreatePanelVersionRequest):Promise<desktop.StoryboardPanelVersionDTO>;

export function CreateScene(arg1:desktop.CreateSceneRequest):Promise<desktop.SceneDTO>;

export function CreateScriptVersion(arg1:desktop.CreateScriptVersionRequest):Promise<desktop.ScriptVersionDTO>;

export function CreateShot(arg1:desktop.CreateShotRequest):Promise<desktop.ShotDTO>;

export function CreateSourceDocument(arg1:desktop.CreateSourceDocumentRequest):Promise<desktop.SourceDocumentDTO>;

export function CreateStageRun(arg1:desktop.CreateStageRunRequest):Promise<desktop.StageRunDTO>;

export function CreateStoryEntity(arg1:desktop.CreateStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function CreateStoryEvent(arg1:desktop.CreateStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function CreateStoryRelation(arg1:desktop.CreateStoryRelationRequest):Promise<desktop.StoryRelationDTO>;

export function CreateStorySkeletonVersion(arg1:desktop.CreateStorySkeletonVersionRequest):Promise<desktop.StorySkeletonVersionDTO>;

export function CreateStoryboardItem(arg1:desktop.CreateStoryboardItemRequest):Promise<desktop.StoryboardItemDTO>;

export function CreateStoryboardVersion(arg1:desktop.CreateStoryboardVersionRequest):Promise<desktop.StoryboardVersionDTO>;

export function CreateWorkflowRun(arg1:desktop.CreateWorkflowRunRequest):Promise<desktop.WorkflowRunDTO>;

export function DiffVersions(arg1:string,arg2:string,arg3:string):Promise<desktop.VersionDiffDTO>;

export function EnsureScript(arg1:string):Promise<desktop.ScriptDTO>;

export function EnsureStoryboard(arg1:string):Promise<desktop.StoryboardDTO>;

export function GetDirectorPlanVersion(arg1:string):Promise<desktop.DirectorPlanVersionDTO>;

export function GetReviewReport(arg1:string):Promise<desktop.ReviewReportDTO>;

export function GetScriptStructure(arg1:string):Promise<desktop.ScriptStructureDTO>;

export function GetStoryboardVersion(arg1:string):Promise<desktop.StoryboardVersionDTO>;

export function ListAdaptationStrategyVersions(arg1:string):Promise<Array<desktop.AdaptationStrategyVersionDTO>>;

export function ListChapters(arg1:string):Promise<Array<desktop.ChapterDTO>>;

export function ListDirectorPlanVersions(arg1:string):Promise<Array<desktop.DirectorPlanVersionDTO>>;

export function ListDomainEvents(arg1:desktop.ListDomainEventsRequest):Promise<Array<desktop.DomainEventDTO>>;

export function ListEpisodes(arg1:string):Promise<Array<desktop.EpisodeDTO>>;

export function ListOpenStaleMarks(arg1:string):Promise<Array<desktop.StaleMarkDTO>>;

export function ListPanelVersions(arg1:string):Promise<Array<desktop.StoryboardPanelVersionDTO>>;

export function ListPanels(arg1:string):Promise<Array<desktop.StoryboardPanelVersionDTO>>;

export function ListScenes(arg1:string):Promise<Array<desktop.SceneDTO>>;

export function ListScriptFieldLocks(arg1:string):Promise<Array<desktop.FieldLockDTO>>;

export function ListShots(arg1:string):Promise<Array<desktop.ShotDTO>>;

export function ListSourceDocuments(arg1:string):Promise<Array<desktop.SourceDocumentDTO>>;

export function ListStageRuns(arg1:string):Promise<Array<desktop.StageRunDTO>>;

export function ListStaleMarks(arg1:string):Promise<Array<desktop.StaleMarkDTO>>;

export function ListStoryConflicts(arg1:string,arg2:string):Promise<Array<desktop.StoryFactConflictDTO>>;

export function ListStoryEntities(arg1:string,arg2:string):Promise<Array<desktop.StoryEntityDTO>>;

export function ListStoryEntityAliases(arg1:string):Promise<Array<desktop.StoryEntityAliasDTO>>;

export function ListStoryEventParticipants(arg1:string):Promise<Array<desktop.StoryEventParticipantDTO>>;

export function ListStoryEvents(arg1:string,arg2:string,arg3:string):Promise<Array<desktop.StoryEventDTO>>;

export function ListStoryFactSources(arg1:string,arg2:string):Promise<Array<desktop.StoryFactSourceDTO>>;

export function ListStoryRelations(arg1:string,arg2:string):Promise<Array<desktop.StoryRelationDTO>>;

export function ListStorySkeletonVersions(arg1:string):Promise<Array<desktop.StorySkeletonVersionDTO>>;

export function ListStoryboardItems(arg1:string):Promise<Array<desktop.StoryboardItemDTO>>;

export function ListStoryboardVersions(arg1:string):Promise<Array<desktop.StoryboardVersionDTO>>;

export function ListWorkflowEvents(arg1:string):Promise<Array<desktop.WorkflowEventDTO>>;

export function ListWorkflowRuns(arg1:string):Promise<Array<desktop.WorkflowRunDTO>>;

export function LockScriptField(arg1:string,arg2:string,arg3:string):Promise<Array<desktop.FieldLockDTO>>;

export function LockStoryEntity(arg1:desktop.LockStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function LockStoryEvent(arg1:desktop.LockStoryEntityRequest):Promise<desktop.StoryEventDTO>;

export function LockableFields():Promise<Array<desktop.LockableFieldDTO>>;

export function ManualEditScript(arg1:desktop.ManualEditScriptRequest):Promise<desktop.ScriptStageResultDTO>;

export function MarkStale(arg1:desktop.MarkStaleRequest):Promise<desktop.StaleMarkDTO>;

export function MergeChapter(arg1:desktop.MergeChapterRequest):Promise<desktop.ChapterDTO>;

export function OpenStoryConflict(arg1:desktop.OpenStoryConflictRequest):Promise<desktop.StoryFactConflictDTO>;

export function ProjectScriptVersion(arg1:desktop.ProjectScriptVersionRequest):Promise<desktop.ProjectScriptVersionResult>;

export function RecordReview(arg1:desktop.RecordReviewRequest):Promise<desktop.ReviewReportDTO>;

export function RejectStoryEntity(arg1:desktop.DecideStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function RejectStoryEvent(arg1:desktop.DecideStoryEventRequest):Promise<desktop.StoryEventDTO>;

export function ResolveStoryConflict(arg1:desktop.ResolveStoryConflictRequest):Promise<desktop.StoryFactConflictDTO>;

export function ReviseChapter(arg1:desktop.ReviseChapterRequest):Promise<desktop.ChapterDTO>;

export function RunImageBatch(arg1:desktop.RunImageBatchRequest):Promise<desktop.RunImageBatchResultDTO>;

export function RunScriptStage(arg1:desktop.RunScriptStageRequest):Promise<desktop.ScriptStageResultDTO>;

export function RunScriptSupervision(arg1:desktop.RunScriptSupervisionRequest):Promise<desktop.ReviewReportDTO>;

export function SaveScriptStructure(arg1:desktop.SaveScriptStructureRequest):Promise<desktop.ScriptVersionDTO>;

export function SetDialogueLineLocked(arg1:desktop.SetDialogueLineLockedRequest):Promise<desktop.DialogueLineDTO>;

export function SetShotOverrides(arg1:desktop.SetShotOverridesRequest):Promise<desktop.DirectorPlanVersionDTO>;

export function SplitChapter(arg1:desktop.SplitChapterRequest):Promise<Array<desktop.ChapterDTO>>;

export function StartScriptRevision(arg1:string):Promise<desktop.StageRunDTO>;

export function SubmitGateDecision(arg1:desktop.SubmitGateDecisionRequest):Promise<desktop.UserGateDecisionDTO>;

export function TransitionStageRun(arg1:desktop.TransitionStageRunRequest):Promise<desktop.StageRunDTO>;

export function TransitionWorkflowRun(arg1:desktop.TransitionWorkflowRunRequest):Promise<desktop.WorkflowRunDTO>;

export function UnlockScriptField(arg1:string,arg2:string):Promise<Array<desktop.FieldLockDTO>>;

export function UnlockStoryEntity(arg1:desktop.LockStoryEntityRequest):Promise<desktop.StoryEntityDTO>;

export function UnlockStoryEvent(arg1:desktop.LockStoryEntityRequest):Promise<desktop.StoryEventDTO>;

export function UpdateEpisodeStatus(arg1:desktop.UpdateEpisodeStatusRequest):Promise<desktop.EpisodeDTO>;

export function UpdateStoryboardItem(arg1:desktop.UpdateStoryboardItemRequest):Promise<desktop.StoryboardItemDTO>;

export function WaiveStaleMark(arg1:desktop.WaiveStaleMarkRequest):Promise<boolean>;
