// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptStoryEntity(arg1) {
  return window['go']['desktop']['DramaBinding']['AcceptStoryEntity'](arg1);
}

export function AcceptStoryEvent(arg1) {
  return window['go']['desktop']['DramaBinding']['AcceptStoryEvent'](arg1);
}

export function AddSourceDocumentVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['AddSourceDocumentVersion'](arg1);
}

export function ApprovePanelImage(arg1) {
  return window['go']['desktop']['DramaBinding']['ApprovePanelImage'](arg1);
}

export function ApproveScriptVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['ApproveScriptVersion'](arg1);
}

export function ClearStaleMark(arg1) {
  return window['go']['desktop']['DramaBinding']['ClearStaleMark'](arg1);
}

export function CountDomainEvents(arg1) {
  return window['go']['desktop']['DramaBinding']['CountDomainEvents'](arg1);
}

export function CreateChapter(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateChapter'](arg1);
}

export function CreateDirectorPlanVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateDirectorPlanVersion'](arg1);
}

export function CreateEpisode(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateEpisode'](arg1);
}

export function CreatePanelVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['CreatePanelVersion'](arg1);
}

export function CreateScene(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateScene'](arg1);
}

export function CreateScriptVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateScriptVersion'](arg1);
}

export function CreateShot(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateShot'](arg1);
}

export function CreateSourceDocument(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateSourceDocument'](arg1);
}

export function CreateStageRun(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStageRun'](arg1);
}

export function CreateStoryEntity(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStoryEntity'](arg1);
}

export function CreateStoryEvent(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStoryEvent'](arg1);
}

export function CreateStoryRelation(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStoryRelation'](arg1);
}

export function CreateStoryboardItem(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStoryboardItem'](arg1);
}

export function CreateStoryboardVersion(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateStoryboardVersion'](arg1);
}

export function CreateWorkflowRun(arg1) {
  return window['go']['desktop']['DramaBinding']['CreateWorkflowRun'](arg1);
}

export function EnsureScript(arg1) {
  return window['go']['desktop']['DramaBinding']['EnsureScript'](arg1);
}

export function EnsureStoryboard(arg1) {
  return window['go']['desktop']['DramaBinding']['EnsureStoryboard'](arg1);
}

export function GetReviewReport(arg1) {
  return window['go']['desktop']['DramaBinding']['GetReviewReport'](arg1);
}

export function ListChapters(arg1) {
  return window['go']['desktop']['DramaBinding']['ListChapters'](arg1);
}

export function ListDomainEvents(arg1) {
  return window['go']['desktop']['DramaBinding']['ListDomainEvents'](arg1);
}

export function ListEpisodes(arg1) {
  return window['go']['desktop']['DramaBinding']['ListEpisodes'](arg1);
}

export function ListOpenStaleMarks(arg1) {
  return window['go']['desktop']['DramaBinding']['ListOpenStaleMarks'](arg1);
}

export function ListPanels(arg1) {
  return window['go']['desktop']['DramaBinding']['ListPanels'](arg1);
}

export function ListScenes(arg1) {
  return window['go']['desktop']['DramaBinding']['ListScenes'](arg1);
}

export function ListShots(arg1) {
  return window['go']['desktop']['DramaBinding']['ListShots'](arg1);
}

export function ListSourceDocuments(arg1) {
  return window['go']['desktop']['DramaBinding']['ListSourceDocuments'](arg1);
}

export function ListStageRuns(arg1) {
  return window['go']['desktop']['DramaBinding']['ListStageRuns'](arg1);
}

export function ListStaleMarks(arg1) {
  return window['go']['desktop']['DramaBinding']['ListStaleMarks'](arg1);
}

export function ListStoryConflicts(arg1, arg2) {
  return window['go']['desktop']['DramaBinding']['ListStoryConflicts'](arg1, arg2);
}

export function ListStoryEntities(arg1, arg2) {
  return window['go']['desktop']['DramaBinding']['ListStoryEntities'](arg1, arg2);
}

export function ListStoryEntityAliases(arg1) {
  return window['go']['desktop']['DramaBinding']['ListStoryEntityAliases'](arg1);
}

export function ListStoryEventParticipants(arg1) {
  return window['go']['desktop']['DramaBinding']['ListStoryEventParticipants'](arg1);
}

export function ListStoryEvents(arg1, arg2, arg3) {
  return window['go']['desktop']['DramaBinding']['ListStoryEvents'](arg1, arg2, arg3);
}

export function ListStoryFactSources(arg1, arg2) {
  return window['go']['desktop']['DramaBinding']['ListStoryFactSources'](arg1, arg2);
}

export function ListStoryRelations(arg1, arg2) {
  return window['go']['desktop']['DramaBinding']['ListStoryRelations'](arg1, arg2);
}

export function ListStoryboardItems(arg1) {
  return window['go']['desktop']['DramaBinding']['ListStoryboardItems'](arg1);
}

export function ListWorkflowEvents(arg1) {
  return window['go']['desktop']['DramaBinding']['ListWorkflowEvents'](arg1);
}

export function ListWorkflowRuns(arg1) {
  return window['go']['desktop']['DramaBinding']['ListWorkflowRuns'](arg1);
}

export function LockStoryEntity(arg1) {
  return window['go']['desktop']['DramaBinding']['LockStoryEntity'](arg1);
}

export function LockStoryEvent(arg1) {
  return window['go']['desktop']['DramaBinding']['LockStoryEvent'](arg1);
}

export function MarkStale(arg1) {
  return window['go']['desktop']['DramaBinding']['MarkStale'](arg1);
}

export function MergeChapter(arg1) {
  return window['go']['desktop']['DramaBinding']['MergeChapter'](arg1);
}

export function OpenStoryConflict(arg1) {
  return window['go']['desktop']['DramaBinding']['OpenStoryConflict'](arg1);
}

export function RecordReview(arg1) {
  return window['go']['desktop']['DramaBinding']['RecordReview'](arg1);
}

export function RejectStoryEntity(arg1) {
  return window['go']['desktop']['DramaBinding']['RejectStoryEntity'](arg1);
}

export function RejectStoryEvent(arg1) {
  return window['go']['desktop']['DramaBinding']['RejectStoryEvent'](arg1);
}

export function ResolveStoryConflict(arg1) {
  return window['go']['desktop']['DramaBinding']['ResolveStoryConflict'](arg1);
}

export function ReviseChapter(arg1) {
  return window['go']['desktop']['DramaBinding']['ReviseChapter'](arg1);
}

export function SplitChapter(arg1) {
  return window['go']['desktop']['DramaBinding']['SplitChapter'](arg1);
}

export function SubmitGateDecision(arg1) {
  return window['go']['desktop']['DramaBinding']['SubmitGateDecision'](arg1);
}

export function TransitionStageRun(arg1) {
  return window['go']['desktop']['DramaBinding']['TransitionStageRun'](arg1);
}

export function TransitionWorkflowRun(arg1) {
  return window['go']['desktop']['DramaBinding']['TransitionWorkflowRun'](arg1);
}

export function UnlockStoryEntity(arg1) {
  return window['go']['desktop']['DramaBinding']['UnlockStoryEntity'](arg1);
}

export function UnlockStoryEvent(arg1) {
  return window['go']['desktop']['DramaBinding']['UnlockStoryEvent'](arg1);
}

export function UpdateEpisodeStatus(arg1) {
  return window['go']['desktop']['DramaBinding']['UpdateEpisodeStatus'](arg1);
}

export function WaiveStaleMark(arg1) {
  return window['go']['desktop']['DramaBinding']['WaiveStaleMark'](arg1);
}
