// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ConfirmChapters(arg1:desktop.ConfirmChaptersRequestDTO):Promise<Array<desktop.ChapterDTO>>;

export function ExtractChapterEventCandidates(arg1:desktop.ExtractChapterRequest):Promise<desktop.ExtractionResultDTO>;

export function ImportDocument(arg1:desktop.ImportDocumentRequest):Promise<desktop.ImportDocumentResult>;

export function PrecheckImport(arg1:desktop.PrecheckImportRequest):Promise<desktop.PrecheckImportResult>;

export function ReadDocumentRange(arg1:desktop.ReadDocumentRangeRequest):Promise<desktop.DocumentRangeDTO>;
