// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortImportUpload(arg1) {
  return window['go']['desktop']['ImportUploadBinding']['AbortImportUpload'](arg1);
}

export function AppendImportUploadChunk(arg1) {
  return window['go']['desktop']['ImportUploadBinding']['AppendImportUploadChunk'](arg1);
}

export function BeginImportUpload(arg1) {
  return window['go']['desktop']['ImportUploadBinding']['BeginImportUpload'](arg1);
}

export function FinishImportUpload(arg1) {
  return window['go']['desktop']['ImportUploadBinding']['FinishImportUpload'](arg1);
}
