// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmChapters(arg1) {
  return window['go']['desktop']['ImportBinding']['ConfirmChapters'](arg1);
}

export function ExtractChapterEventCandidates(arg1) {
  return window['go']['desktop']['ImportBinding']['ExtractChapterEventCandidates'](arg1);
}

export function ImportDocument(arg1) {
  return window['go']['desktop']['ImportBinding']['ImportDocument'](arg1);
}

export function PrecheckImport(arg1) {
  return window['go']['desktop']['ImportBinding']['PrecheckImport'](arg1);
}

export function ReadDocumentRange(arg1) {
  return window['go']['desktop']['ImportBinding']['ReadDocumentRange'](arg1);
}
