// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AbortImportUpload(arg1:string):Promise<void>;

export function AppendImportUploadChunk(arg1:desktop.AppendImportUploadChunkRequest):Promise<void>;

export function BeginImportUpload(arg1:desktop.BeginImportUploadRequest):Promise<desktop.BeginImportUploadResult>;

export function FinishImportUpload(arg1:desktop.FinishImportUploadRequest):Promise<desktop.ImportDocumentResult>;
