// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJobs(arg1) {
  return window['go']['desktop']['JobsBinding']['CancelJobs'](arg1);
}

export function GetJob(arg1) {
  return window['go']['desktop']['JobsBinding']['GetJob'](arg1);
}

export function GetQueueStatus() {
  return window['go']['desktop']['JobsBinding']['GetQueueStatus']();
}

export function JobAttempts(arg1) {
  return window['go']['desktop']['JobsBinding']['JobAttempts'](arg1);
}

export function ListJobs(arg1) {
  return window['go']['desktop']['JobsBinding']['ListJobs'](arg1);
}

export function PauseQueue() {
  return window['go']['desktop']['JobsBinding']['PauseQueue']();
}

export function ReadResultFile(arg1) {
  return window['go']['desktop']['JobsBinding']['ReadResultFile'](arg1);
}

export function ResumeQueue() {
  return window['go']['desktop']['JobsBinding']['ResumeQueue']();
}

export function RetryFailedJobs(arg1) {
  return window['go']['desktop']['JobsBinding']['RetryFailedJobs'](arg1);
}

export function SubmitImageJob(arg1) {
  return window['go']['desktop']['JobsBinding']['SubmitImageJob'](arg1);
}
