// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CancelJobs(arg1:Array<string>):Promise<number>;

export function GetJob(arg1:string):Promise<desktop.JobDTO>;

export function GetQueueStatus():Promise<desktop.QueueSummaryDTO>;

export function JobAttempts(arg1:string):Promise<Array<desktop.JobAttemptDTO>>;

export function ListJobs(arg1:desktop.ListJobsRequest):Promise<Array<desktop.JobDTO>>;

export function PauseQueue():Promise<void>;

export function ReadResultFile(arg1:string):Promise<desktop.JobResultFileContent>;

export function ResumeQueue():Promise<void>;

export function RetryFailedJobs(arg1:Array<string>):Promise<number>;

export function SubmitAudioJob(arg1:desktop.SubmitAudioJobRequest):Promise<desktop.JobDTO>;

export function SubmitEffectJob(arg1:desktop.SubmitEffectJobRequest):Promise<desktop.JobDTO>;

export function SubmitImageJob(arg1:desktop.SubmitImageJobRequest):Promise<desktop.JobDTO>;

export function SubmitVideoBatch(arg1:desktop.SubmitVideoBatchRequest):Promise<desktop.SubmitVideoBatchResultDTO>;

export function SubmitVideoJob(arg1:desktop.SubmitVideoJobRequest):Promise<desktop.JobDTO>;
