// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortLegacyFile(arg1:string):Promise<void>;

export function AppendLegacyFile(arg1:string,arg2:string):Promise<number>;

export function BeginLegacyFile(arg1:string,arg2:string,arg3:number):Promise<string>;

export function FinishLegacyFile(arg1:string,arg2:string):Promise<boolean>;

export function PendingUploads():Promise<number>;
