// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortLegacyFile(arg1) {
  return window['go']['desktop']['LegacyUploadBinding']['AbortLegacyFile'](arg1);
}

export function AppendLegacyFile(arg1, arg2) {
  return window['go']['desktop']['LegacyUploadBinding']['AppendLegacyFile'](arg1, arg2);
}

export function BeginLegacyFile(arg1, arg2, arg3) {
  return window['go']['desktop']['LegacyUploadBinding']['BeginLegacyFile'](arg1, arg2, arg3);
}

export function FinishLegacyFile(arg1, arg2) {
  return window['go']['desktop']['LegacyUploadBinding']['FinishLegacyFile'](arg1, arg2);
}

export function PendingUploads() {
  return window['go']['desktop']['LegacyUploadBinding']['PendingUploads']();
}
