// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function ApproveExport(arg1:desktop.ApproveExportRequest):Promise<desktop.ExportRecordDTO>;

export function ApproveSubtitleTrack(arg1:desktop.ApproveSubtitleTrackRequest):Promise<desktop.SubtitleTrackDTO>;

export function DraftSubtitles(arg1:desktop.DraftSubtitlesRequest):Promise<desktop.SubtitleDraftDTO>;

export function EditSubtitleCues(arg1:string,arg2:Array<desktop.SubtitleCueEdit>):Promise<Array<desktop.SubtitleCueDTO>>;

export function ExportManifestDocument(arg1:desktop.ExportManifestDocumentRequest):Promise<desktop.DocumentDTO>;

export function ExportScript(arg1:desktop.ExportScriptRequest):Promise<desktop.DocumentDTO>;

export function ExportShotList(arg1:desktop.ExportShotListRequest):Promise<desktop.DocumentDTO>;

export function ExportSubtitles(arg1:desktop.ExportSubtitlesRequest):Promise<string>;

export function ListExports(arg1:string):Promise<Array<desktop.ExportRecordDTO>>;

export function ListSubtitleCues(arg1:string):Promise<Array<desktop.SubtitleCueDTO>>;

export function ListSubtitleTracks(arg1:string):Promise<Array<desktop.SubtitleTrackDTO>>;

export function MediaCapability():Promise<desktop.MediaCapabilityDTO>;

export function MissingSubtitleLines(arg1:string):Promise<Array<desktop.MissingLineDTO>>;

export function ReadTimeline(arg1:desktop.TimelineRequest):Promise<desktop.TimelineDTO>;

export function RunExport(arg1:desktop.RunExportRequest):Promise<desktop.ExportRecordDTO>;

export function SaveDocument(arg1:desktop.SaveDocumentRequest):Promise<desktop.SaveFileResultDTO>;

export function SaveExport(arg1:desktop.SaveExportRequest):Promise<desktop.SaveFileResultDTO>;

export function SubmitExportForReview(arg1:desktop.SubmitExportForReviewRequest):Promise<desktop.ExportRecordDTO>;

export function SubmitSubtitleTrackForReview(arg1:desktop.SubmitSubtitleTrackForReviewRequest):Promise<desktop.SubtitleTrackDTO>;
