// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveExport(arg1) {
  return window['go']['desktop']['MediaBinding']['ApproveExport'](arg1);
}

export function ApproveSubtitleTrack(arg1) {
  return window['go']['desktop']['MediaBinding']['ApproveSubtitleTrack'](arg1);
}

export function DraftSubtitles(arg1) {
  return window['go']['desktop']['MediaBinding']['DraftSubtitles'](arg1);
}

export function EditSubtitleCues(arg1, arg2) {
  return window['go']['desktop']['MediaBinding']['EditSubtitleCues'](arg1, arg2);
}

export function ExportManifestDocument(arg1) {
  return window['go']['desktop']['MediaBinding']['ExportManifestDocument'](arg1);
}

export function ExportScript(arg1) {
  return window['go']['desktop']['MediaBinding']['ExportScript'](arg1);
}

export function ExportShotList(arg1) {
  return window['go']['desktop']['MediaBinding']['ExportShotList'](arg1);
}

export function ExportSubtitles(arg1) {
  return window['go']['desktop']['MediaBinding']['ExportSubtitles'](arg1);
}

export function ListExports(arg1) {
  return window['go']['desktop']['MediaBinding']['ListExports'](arg1);
}

export function ListSubtitleCues(arg1) {
  return window['go']['desktop']['MediaBinding']['ListSubtitleCues'](arg1);
}

export function ListSubtitleTracks(arg1) {
  return window['go']['desktop']['MediaBinding']['ListSubtitleTracks'](arg1);
}

export function MediaCapability() {
  return window['go']['desktop']['MediaBinding']['MediaCapability']();
}

export function MissingSubtitleLines(arg1) {
  return window['go']['desktop']['MediaBinding']['MissingSubtitleLines'](arg1);
}

export function ReadTimeline(arg1) {
  return window['go']['desktop']['MediaBinding']['ReadTimeline'](arg1);
}

export function RunExport(arg1) {
  return window['go']['desktop']['MediaBinding']['RunExport'](arg1);
}

export function SaveDocument(arg1) {
  return window['go']['desktop']['MediaBinding']['SaveDocument'](arg1);
}

export function SaveExport(arg1) {
  return window['go']['desktop']['MediaBinding']['SaveExport'](arg1);
}

export function SubmitExportForReview(arg1) {
  return window['go']['desktop']['MediaBinding']['SubmitExportForReview'](arg1);
}

export function SubmitSubtitleTrackForReview(arg1) {
  return window['go']['desktop']['MediaBinding']['SubmitSubtitleTrackForReview'](arg1);
}
