// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function DeleteMemory(arg1:desktop.DeleteMemoryRequest):Promise<desktop.MemoryDeleteResultDTO>;

export function GetMemory(arg1:string):Promise<desktop.MemoryDTO>;

export function LinkMemory(arg1:desktop.MemoryLinkRequest):Promise<void>;

export function ListMemories(arg1:desktop.MemoryQuery):Promise<Array<desktop.MemoryDTO>>;

export function ListMemoryEntityLinks(arg1:string):Promise<Array<desktop.MemoryEntityLinkDTO>>;

export function ListSummarySources(arg1:string):Promise<Array<desktop.MemorySummarySourceDTO>>;

export function PreviewMemoryRecall(arg1:desktop.RecallPreviewRequest):Promise<desktop.MemoryRecallPreviewDTO>;

export function RebuildMemoryEmbedding(arg1:desktop.RebuildMemoryEmbeddingRequest):Promise<desktop.MemoryRebuildResultDTO>;

export function RememberFact(arg1:desktop.RememberFactRequest):Promise<desktop.MemoryDTO>;

export function SetMemoryLocked(arg1:desktop.MemoryPinRequest):Promise<boolean>;

export function SummarizeMemory(arg1:desktop.SummarizeMemoryRequest):Promise<desktop.MemorySummarizeResultDTO>;

export function UpdateMemoryContent(arg1:desktop.MemoryEditRequest):Promise<boolean>;
