// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteMemory(arg1) {
  return window['go']['desktop']['MemoryBinding']['DeleteMemory'](arg1);
}

export function GetMemory(arg1) {
  return window['go']['desktop']['MemoryBinding']['GetMemory'](arg1);
}

export function LinkMemory(arg1) {
  return window['go']['desktop']['MemoryBinding']['LinkMemory'](arg1);
}

export function ListMemories(arg1) {
  return window['go']['desktop']['MemoryBinding']['ListMemories'](arg1);
}

export function ListMemoryEntityLinks(arg1) {
  return window['go']['desktop']['MemoryBinding']['ListMemoryEntityLinks'](arg1);
}

export function ListSummarySources(arg1) {
  return window['go']['desktop']['MemoryBinding']['ListSummarySources'](arg1);
}

export function PreviewMemoryRecall(arg1) {
  return window['go']['desktop']['MemoryBinding']['PreviewMemoryRecall'](arg1);
}

export function RebuildMemoryEmbedding(arg1) {
  return window['go']['desktop']['MemoryBinding']['RebuildMemoryEmbedding'](arg1);
}

export function RememberFact(arg1) {
  return window['go']['desktop']['MemoryBinding']['RememberFact'](arg1);
}

export function SetMemoryLocked(arg1) {
  return window['go']['desktop']['MemoryBinding']['SetMemoryLocked'](arg1);
}

export function SummarizeMemory(arg1) {
  return window['go']['desktop']['MemoryBinding']['SummarizeMemory'](arg1);
}

export function UpdateMemoryContent(arg1) {
  return window['go']['desktop']['MemoryBinding']['UpdateMemoryContent'](arg1);
}
