// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AbortSnapshotUpload(arg1:string):Promise<void>;

export function AppendSnapshotChunk(arg1:desktop.AppendSnapshotChunkRequest):Promise<void>;

export function BeginSnapshotUpload(arg1:desktop.BeginSnapshotUploadRequest):Promise<desktop.BeginSnapshotUploadResult>;

export function FinishSnapshotUpload(arg1:desktop.FinishSnapshotUploadRequest):Promise<desktop.FinishSnapshotUploadResult>;
