// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortSnapshotUpload(arg1) {
  return window['go']['desktop']['MonoformBinding']['AbortSnapshotUpload'](arg1);
}

export function AppendSnapshotChunk(arg1) {
  return window['go']['desktop']['MonoformBinding']['AppendSnapshotChunk'](arg1);
}

export function BeginSnapshotUpload(arg1) {
  return window['go']['desktop']['MonoformBinding']['BeginSnapshotUpload'](arg1);
}

export function FinishSnapshotUpload(arg1) {
  return window['go']['desktop']['MonoformBinding']['FinishSnapshotUpload'](arg1);
}
