// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AbortMusicImport(arg1:string):Promise<void>;

export function AppendMusicChunk(arg1:desktop.AppendMusicChunkRequest):Promise<void>;

export function BeginMusicImport(arg1:desktop.BeginMusicImportRequest):Promise<desktop.BeginMusicImportResult>;

export function FinishMusicImport(arg1:desktop.FinishMusicImportRequest):Promise<desktop.FinishMusicImportResult>;
