// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMusicImport(arg1) {
  return window['go']['desktop']['MusicImportBinding']['AbortMusicImport'](arg1);
}

export function AppendMusicChunk(arg1) {
  return window['go']['desktop']['MusicImportBinding']['AppendMusicChunk'](arg1);
}

export function BeginMusicImport(arg1) {
  return window['go']['desktop']['MusicImportBinding']['BeginMusicImport'](arg1);
}

export function FinishMusicImport(arg1) {
  return window['go']['desktop']['MusicImportBinding']['FinishMusicImport'](arg1);
}
