// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEdge(arg1) {
  return window['go']['desktop']['ProjectsBinding']['CreateEdge'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['desktop']['ProjectsBinding']['CreateProject'](arg1);
}

export function DeleteEdges(arg1) {
  return window['go']['desktop']['ProjectsBinding']['DeleteEdges'](arg1);
}

export function DeleteNodes(arg1) {
  return window['go']['desktop']['ProjectsBinding']['DeleteNodes'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['ProjectsBinding']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['desktop']['ProjectsBinding']['GetProject'](arg1);
}

export function ImportProjects(arg1) {
  return window['go']['desktop']['ProjectsBinding']['ImportProjects'](arg1);
}

export function ListImports(arg1) {
  return window['go']['desktop']['ProjectsBinding']['ListImports'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['desktop']['ProjectsBinding']['ListProjects'](arg1);
}

export function LoadCanvas(arg1) {
  return window['go']['desktop']['ProjectsBinding']['LoadCanvas'](arg1);
}

export function MoveNodes(arg1) {
  return window['go']['desktop']['ProjectsBinding']['MoveNodes'](arg1);
}

export function PrecheckImport(arg1) {
  return window['go']['desktop']['ProjectsBinding']['PrecheckImport'](arg1);
}

export function RenameProject(arg1) {
  return window['go']['desktop']['ProjectsBinding']['RenameProject'](arg1);
}

export function SaveChatSession(arg1) {
  return window['go']['desktop']['ProjectsBinding']['SaveChatSession'](arg1);
}

export function SetProjectStatus(arg1) {
  return window['go']['desktop']['ProjectsBinding']['SetProjectStatus'](arg1);
}

export function UpdateViewport(arg1) {
  return window['go']['desktop']['ProjectsBinding']['UpdateViewport'](arg1);
}

export function UpsertNode(arg1) {
  return window['go']['desktop']['ProjectsBinding']['UpsertNode'](arg1);
}
