// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function CreateEdge(arg1:desktop.CreateEdgeRequest):Promise<desktop.CanvasEdgeDTO>;

export function CreateProject(arg1:desktop.CreateProjectRequest):Promise<desktop.ProjectDTO>;

export function DeleteEdges(arg1:Array<string>):Promise<number>;

export function DeleteNodes(arg1:Array<string>):Promise<number>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<desktop.ProjectDTO>;

export function ImportProjects(arg1:desktop.ImportProjectsRequest):Promise<string>;

export function ListImports(arg1:number):Promise<string>;

export function ListProjects(arg1:desktop.ListProjectsRequest):Promise<Array<desktop.ProjectDTO>>;

export function LoadCanvas(arg1:string):Promise<desktop.CanvasSnapshotDTO>;

export function MoveNodes(arg1:desktop.MoveNodesRequest):Promise<number>;

export function PrecheckImport(arg1:string):Promise<string>;

export function RenameProject(arg1:desktop.RenameProjectRequest):Promise<desktop.ProjectDTO>;

export function SaveChatSession(arg1:desktop.SaveChatSessionRequest):Promise<desktop.CanvasChatSessionDTO>;

export function SetProjectStatus(arg1:desktop.SetProjectStatusRequest):Promise<desktop.ProjectDTO>;

export function UpdateViewport(arg1:desktop.UpdateViewportRequest):Promise<desktop.CanvasSnapshotDTO>;

export function UpsertNode(arg1:desktop.UpsertNodeRequest):Promise<desktop.CanvasNodeDTO>;
