// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['desktop']['ProvidersBinding']['CancelStream'](arg1);
}

export function CheckHealth(arg1) {
  return window['go']['desktop']['ProvidersBinding']['CheckHealth'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['desktop']['ProvidersBinding']['DeleteConfig'](arg1);
}

export function GenerateText(arg1) {
  return window['go']['desktop']['ProvidersBinding']['GenerateText'](arg1);
}

export function ListConfigs() {
  return window['go']['desktop']['ProvidersBinding']['ListConfigs']();
}

export function SaveConfig(arg1) {
  return window['go']['desktop']['ProvidersBinding']['SaveConfig'](arg1);
}

export function StreamText(arg1) {
  return window['go']['desktop']['ProvidersBinding']['StreamText'](arg1);
}
