// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {provider} from '../models';
import {providers} from '../models';

export function ActivateManifest(arg1:desktop.ActivateManifestRequest):Promise<void>;

export function CancelStream(arg1:string):Promise<void>;

export function CheckHealth(arg1:string):Promise<provider.HealthState>;

export function DeleteConfig(arg1:string):Promise<void>;

export function GenerateText(arg1:desktop.TextRequestDTO):Promise<providers.TextResult>;

export function ListConfigs():Promise<Array<providers.ConfigDTO>>;

export function ListManifestVersions(arg1:string):Promise<Array<desktop.ManifestVersionDTO>>;

export function PreviewManifest(arg1:string):Promise<desktop.ManifestPreviewDTO>;

export function SaveConfig(arg1:desktop.ProviderConfigRequest):Promise<providers.ConfigDTO>;

export function SaveManifest(arg1:desktop.SaveManifestRequest):Promise<desktop.ManifestVersionDTO>;

export function StreamText(arg1:desktop.TextRequestDTO):Promise<string>;
