// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';
import {secrets} from '../models';

export function Delete(arg1:string):Promise<void>;

export function Set(arg1:desktop.SetSecretRequest):Promise<void>;

export function Status(arg1:string):Promise<secrets.Status>;
