// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['desktop']['SecretsBinding']['Delete'](arg1);
}

export function Set(arg1) {
  return window['go']['desktop']['SecretsBinding']['Set'](arg1);
}

export function Status(arg1) {
  return window['go']['desktop']['SecretsBinding']['Status'](arg1);
}
