// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoBackup() {
  return window['go']['desktop']['SettingsBinding']['GetAutoBackup']();
}

export function SetAutoBackup(arg1, arg2) {
  return window['go']['desktop']['SettingsBinding']['SetAutoBackup'](arg1, arg2);
}
