// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function GetAutoBackup():Promise<desktop.AutoBackupSettings>;

export function SetAutoBackup(arg1:desktop.AutoBackupSettings,arg2:number):Promise<void>;
