// Package productionpipeline drives the production stages: the director's plan, the
// asset gap analysis, generation, the storyboard table, the panels, and the image
// batch that fills them.
//
// # What this package is
//
// It is a LAYER over `application/stagepipeline`, in the sense that package's `Layer`
// interface defines: it states which agents serve which stage, which version family a
// stage writes, how to approve one, and how to write a user's own version. The stage
// machine itself — the attempt, the FIX read-back, the gate's ordering, the manual
// edit's two-step — is the mechanism's, and WP-09 extracted it from the script pipeline
// precisely so this package would not be a second implementation of it.
//
// # What is this package's own
//
// Two things the mechanism cannot know, because they are about PRODUCTION rather than
// about stages:
//
//   - the BATCH. `RunImageBatch` submits one job per candidate per shot, bounded by a
//     concurrency limit, and AC-BOARD-003's three requirements — two candidates a shot,
//     an observed limit, and no duplicate submission across a restart — are all about
//     that loop rather than about a stage.
//   - the GATE. AC-BOARD-001's "未通过时阻止批量生成" is a question about four separate
//     approvals plus a gap report, and `CheckStoryboardGate` is where they are read.
package productionpipeline

import (
	"context"
	"strings"

	agentruntime "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/agentruntime"
	appassets "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/assets"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/stagepipeline"
	appstoryboard "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/storyboard"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/agent"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/workflow"
)

// Stage is one of the stages this pipeline drives.
type Stage = stagepipeline.Stage

const (
	// StageDirectorPlan is FR-060's planning stage.
	//
	// It is WP-09's addition to the stage vocabulary, and AGENT_CONTRACTS §10.1 is what
	// configures it: supervision conditional, user gate required. A stage the
	// specification names has to exist as a stage, or the policy lookup falls through to
	// the default and the settings the document gives it are lost.
	StageDirectorPlan Stage = "director_plan"
	// StageAssetGapAnalysis is FR-050's "资产缺口分析": what the script needs and the
	// library does not have.
	StageAssetGapAnalysis Stage = "asset_gap_analysis"
	// StageAssetGeneration is where candidate assets are produced.
	StageAssetGeneration Stage = "asset_generation"
	// StageStoryboardTable is FR-070's table: one row per shot.
	StageStoryboardTable Stage = "storyboard_table"
	// StageStoryboardPanel is where a shot's panels are written.
	StageStoryboardPanel Stage = "storyboard_panel_generation"
	// StageFinalEpisode is FR-100's `final_episode` and AGENT_CONTRACTS section 11.4's Final Ruleset.
	//
	// It is the one stage whose artifact is an EPISODE rather than a version, and that is what the
	// clause "所有必需 Shot 有批准视频" is about: the final review reads the whole production and reports
	// whether it may be exported, so its subject is the episode's assembled state.
	StageFinalEpisode Stage = "final_episode"
)

// Stages lists the six in pipeline order.
//
// The order is the dependency order and not a preference: a plan is written from a script, a board
// from both, a panel from a board's row, and the final review from all of it. `storyboard_image` is
// NOT here — §10.1's sixth production stage — because images are generated by JOBS rather than by an
// agent run, and `RunImageBatch` is what drives them.
//
// `video_generation` is absent for the same reason, and it is worth stating because the roadmap lists
// it beside this one: media generation is a Job and not an agent tool, which is AGENT_CONTRACTS
// section 19's own note ("媒体生成本身由 Job/Provider Service 执行，不让 LLM 阻塞等待大文件") and
// ADR-0011 section 6's ruling. A stage that ran a video job inline would block a prompt on a file
// download, so `SubmitVideoJob` is the command that starts one and no agent serves the stage.
func Stages() []Stage {
	return []Stage{
		StageDirectorPlan,
		StageAssetGapAnalysis,
		StageAssetGeneration,
		StageStoryboardTable,
		StageStoryboardPanel,
		StageFinalEpisode,
	}
}

// WriteToolPrefix is what every production write tool's key starts with.
const WriteToolPrefix = "storyboard.create_"

// stageAgents is the STATED map from a stage to the two agents that serve it.
//
// A stage without an entry is REFUSED rather than guessed, which is the fail-closed
// direction: a stage whose supervisor is unknown would run unsupervised — silently
// skipping the review its policy requires — or be supervised by whatever agent a
// substring match found, which is worse because the report would look real.
var stageAgents = map[Stage]stagepipeline.StageAgents{
	StageDirectorPlan: {
		Execution:    "production.execution.director_plan",
		Supervision:  "production.supervision.director_plan",
		ArtifactType: "director_plan_version",
	},
	StageAssetGapAnalysis: {
		Execution: "production.execution.asset_analysis",
		// NO SUPERVISOR, and that is §10.1's own setting: asset_analysis is the one
		// production stage the document marks `supervision: false`. Its output is a list
		// of facts about the library — each line either names an asset that exists or
		// says one does not — so there is nothing for a ruleset to judge that the
		// database does not already answer.
		Supervision:  "",
		ArtifactType: "asset_gap_report",
	},
	StageAssetGeneration: {
		Execution:    "production.execution.asset_generation_plan",
		Supervision:  "",
		ArtifactType: "asset_version",
	},
	StageStoryboardTable: {
		Execution:    "production.execution.storyboard_table",
		Supervision:  "production.supervision.storyboard_table",
		ArtifactType: "storyboard_version",
	},
	StageStoryboardPanel: {
		Execution:    "production.execution.storyboard_panel",
		Supervision:  "production.supervision.storyboard_panel",
		ArtifactType: "storyboard_panel_version",
	},
	StageFinalEpisode: {
		Execution: "production.execution.final_episode",
		// The Final Supervisor, which AC-MEDIA-003 names as a clause of its own:
		//
		//	## AC-MEDIA-003 Timeline/MP4
		//	- ordered Shots；
		//	- audio/subtitle；
		//	- replace clip；
		//	- export；
		//	- Final Supervisor；
		//	- output playable；
		//	- manifest traceability。
		//
		// The division of labour is section 11.4's own: the deterministic ruleset above answers the
		// eight hard clauses — approved media per shot, audio and subtitle completeness, files
		// present, stale marks, empty media, total duration, licence metadata, export parameters —
		// and the supervisor is asked about what is left, which is whether the film the rows describe
		// is the film the episode intended.
		//
		// THE REVIEW IS WHERE THE TWO HALVES MERGE, and that is not a description of this line: the
		// stage machine runs the deterministic pass BEFORE it asks the model and passes the findings
		// into its task, so a supervisor is told what a join found rather than being asked to notice
		// it. `stagepipeline.RunSupervision` is the mechanism and `FinalRuleset` is the rules this
		// stage contributes to it.
		Supervision:  "production.supervision.final_episode",
		ArtifactType: "episode",
	},
}

// AgentsForStage returns the agents that serve one stage.
func AgentsForStage(stage Stage) (stagepipeline.StageAgents, bool) {
	agents, ok := stageAgents[stage]
	if !ok {
		return stagepipeline.StageAgents{}, false
	}
	agents.WriteToolPrefix = WriteToolPrefix
	return agents, true
}

// IsProductionStage reports whether this layer drives a stage, for the reason
// `scriptpipeline.IsScriptStage` states.
func IsProductionStage(stage string) bool {
	_, ok := stageAgents[Stage(stage)]
	return ok
}

// Layer adapts this package's knowledge to the generic mechanism.
//
// It holds the three services whose APPROVALS are the real ones, because a stage's gate
// makes its artifact the one in force: the director plan and the storyboard have their own
// commands, the gap report has one with its own precondition, and an asset version is
// approved through the assets service that performs the impact analysis §8.2 requires.
// A layer that "approved" any of them itself would be a second approval path with a second
// set of rules.
type Layer struct {
	storyboard *appstoryboard.Service
	gaps       *appassets.GapService
	assets     *appassets.Service
}

// NewLayer builds the production layer over its services.
func NewLayer(storyboardService *appstoryboard.Service, gapService *appassets.GapService, assetService *appassets.Service) *Layer {
	return &Layer{storyboard: storyboardService, gaps: gapService, assets: assetService}
}

// Compile-time proof that this layer satisfies the mechanism.
var _ stagepipeline.Layer = (*Layer)(nil)

// Name identifies the layer in the actor every transition records.
func (l *Layer) Name() string { return "productionpipeline" }

// Stages lists the five stages in pipeline order.
func (l *Layer) Stages() []Stage { return Stages() }

// AgentsFor returns the agents serving one stage.
func (l *Layer) AgentsFor(stage Stage) (stagepipeline.StageAgents, bool) {
	return AgentsForStage(stage)
}

// StateFor renders the prompt's workflow-state layer for one attempt.
func (l *Layer) StateFor(attempt workflow.StageRun, request stagepipeline.StageRequest) string {
	fields, _ := request.State.(StateFields)
	return renderState(attempt, request, fields)
}

// Approve puts one version in force for its family, through that family's own command.
//
// EACH STAGE DELEGATES RATHER THAN REIMPLEMENTING, and the three paths differ on purpose:
//
//   - `director_plan` and `storyboard_table` call the storyboard service's approvals,
//     which supersede the previous version and record a governance event.
//   - `asset_gap_analysis` calls the GAP service's, whose approval refuses a report that
//     still has a required asset missing. That precondition is the whole reason the report
//     cannot be approved through a generic path.
//   - `asset_generation` calls the ASSETS service's, which performs the impact analysis
//     §8.2 requires before an approval switch and refuses without the caller's
//     acknowledgement. The acknowledgement is supplied here because the gate IS that
//     acknowledgement: the user reviewed the candidate and decided.
//
// `storyboard_panel_generation` is REFUSED, and that is §9.5's rule rather than an
// omission: a panel's image is approved by being made the panel's canonical image, which
// is `ApprovePanelImage` — a command whose subject is the SCENE's image rather than the
// stage's artifact. An approval through this gate would have to guess which candidate.
func (l *Layer) Approve(ctx context.Context, stage Stage, versionID, traceID string) error {
	switch stage {
	case StageDirectorPlan:
		if l == nil || l.storyboard == nil {
			return agent.UnavailableError()
		}
		_, err := l.storyboard.ApproveDirectorPlanVersion(ctx, appstoryboard.ApproveDirectorPlanVersionRequest{
			VersionID: versionID, TraceID: traceID,
		})
		return err
	case StageStoryboardTable:
		if l == nil || l.storyboard == nil {
			return agent.UnavailableError()
		}
		_, err := l.storyboard.ApproveStoryboardVersion(ctx, appstoryboard.ApproveStoryboardVersionRequest{
			VersionID: versionID, TraceID: traceID,
		})
		return err
	case StageAssetGapAnalysis:
		if l == nil || l.gaps == nil {
			return agent.UnavailableError()
		}
		_, err := l.gaps.ApproveGapReport(ctx, appassets.ApproveGapReportRequest{
			ReportID: versionID, TraceID: traceID,
		})
		return err
	case StageAssetGeneration:
		if l == nil || l.assets == nil {
			return agent.UnavailableError()
		}
		_, err := l.assets.ApproveVersion(ctx, appassets.ApproveVersionRequest{
			VersionID: versionID,
			// The gate IS the acknowledgement: the user reviewed the candidate and decided,
			// which is what §8.2 asks for. A caller reaching this method has already been
			// through `ApplyUserGate`, which is the only route here.
			ImpactAcknowledged: true,
		})
		return err
	case StageStoryboardPanel:
		return agent.InvalidError(
			"A panel's image is approved by making it the panel's canonical image, which this gate cannot choose.")
	case StageFinalEpisode:
		// The final stage's artifact is the EXPORT, and its approval has its own command for the same
		// reason the panel's does: what is put in force is a file, and the command that does it —
		// `MediaBinding.ApproveExport`, which supersedes the previous export and records the trace —
		// is the only path that can say which file. A gate that "approved" an episode would be
		// approving nothing, because an episode is not a version.
		return agent.InvalidError(
			"An episode's release is approved by approving its export, which this gate cannot choose. " +
				"Approve the export you reviewed.")
	default:
		return agent.InvalidError("This pipeline does not drive the stage " + string(stage) + ".")
	}
}

// Locks returns the field pins a version carries.
//
// The production families have NO lock table, and that is not an omission: WP-08 built
// `script_version_field_locks` for AC-SCRIPT-002's FIX scenario, where a user pins the
// fields a model got right. A storyboard FIX's unit is the ITEM rather than the field —
// AC-BOARD-002 requires that "其他 Shot 不变", which is a statement about rows — so the
// mechanism's per-field locks have nothing to attach to here.
//
// It answers nil rather than refusing, which is what the port's comment allows: "this
// layer pins nothing" is an answer, and an error would stop a revision that is fine.
func (l *Layer) Locks(ctx context.Context, stage Stage, versionID string) ([]agentruntime.LockedRef, error) {
	if _, err := familyOfStage(stage); err != nil {
		return nil, err
	}
	return nil, nil
}

// WriteVersion writes the user's own version for a manual edit.
//
// It is REFUSED for every production stage, and the refusal is stated rather than silently
// returning an empty id: a manual edit's payload for these artifacts is a director plan, a
// storyboard with its rows, or a panel — three shapes none of which this build's
// manual-edit command has a form for. A user editing a board does it through the table
// UI's own commands, so routing that through the stage machine's manual edit would be a
// second write path with a second set of rules.
func (l *Layer) WriteVersion(ctx context.Context, stage Stage, agents stagepipeline.StageAgents, request stagepipeline.ManualEditRequest) (string, error) {
	if _, err := familyOfStage(stage); err != nil {
		return "", err
	}
	return "", agent.InvalidError("This pipeline does not write user versions through a manual edit.")
}

// familyOfStage maps a stage to the version family its artifact belongs to.
//
// It resolves exactly the stages this layer drives, which is what makes it the stage
// check `Approve`, `Locks` and `WriteVersion` all use.
func familyOfStage(stage Stage) (string, error) {
	switch stage {
	case StageDirectorPlan:
		return "director_plan", nil
	case StageAssetGapAnalysis:
		return "asset_gap_report", nil
	case StageAssetGeneration:
		return "asset_version", nil
	case StageStoryboardTable:
		return "storyboard_version", nil
	case StageStoryboardPanel:
		return "storyboard_panel_version", nil
	case StageFinalEpisode:
		// The episode, because that is what the stage's subject is. It is not a version family of its
		// own and the stage writes none: the artifact it reports IS the episode, and the export that
		// a person approves afterwards has its own family through `MediaBinding`.
		return "episode", nil
	default:
		return "", agent.InvalidError("This pipeline does not drive the stage " + string(stage) + ".")
	}
}

// StateFields are the production layer's extra state for the prompt's state layer.
type StateFields struct {
	EpisodeID             string
	ScriptVersionID       string
	DirectorPlanVersionID string
	StoryboardID          string
	StoryboardVersionID   string
	StoryboardItemID      string
	AssetGapReportID      string
	// ShotIDs are the shots the board stage boards, in the script's order. They travel
	// because the stage's write tool CHECKS every row's citation against the script's own
	// shots — `storyboard_items.shot_id` has no foreign key, so the handler is what keeps
	// an invented id out — and a model that could not see the ids could only guess them.
	ShotIDs []string
	// AssetIDs are the assets the generation stage may write candidate versions against.
	//
	// They travel for the same reason `ShotIDs` does: the stage's write tool resolves the asset it
	// is told to write against and REFUSES an unknown id, so the ids have to be visible to the model
	// rather than guessed. The gap report says which assets the episode needs by NAME; resolving
	// those names to rows is a user's act, and its result is what this field carries.
	AssetIDs []string
}

// itoa renders a small non-negative integer without importing strconv for one call site.
func itoa(value int) string {
	if value <= 0 {
		return "0"
	}
	digits := ""
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	return digits
}

// trimmed is the small helper every call site here uses, so a padded identifier is
// treated the same way everywhere.
func trimmed(value string) string { return strings.TrimSpace(value) }
