const fs = require("fs");
const p = "docs/implementation/STATUS.md";
let s = fs.readFileSync(p, "utf8");

s = s.replace(
    "> Last updated: 2026-09-15",
    "> Last updated: 2026-09-17",
);
s = s.replace(
    "> Current work package: **WP-03 — Persistent Job Manager 与多模态 Provider**\n> Status: **COMPLETE for the WP-03 scope recorded in section 0c** (job tables and state machine, scheduler/worker/lease/retry, startup recovery, OpenAI- and Gemini-compatible image adapters, async video and audio contracts with mocks, result pipeline into the FileStore, narrow job bindings, Job Center UI, image generation routed through Go, scans). WP-01 and WP-02 remain COMPLETE for their recorded scopes.",
    "> Current work package: **WP-04 — Legacy 项目迁移与画布后端适配**\n> Status: **COMPLETE for the WP-04 scope recorded in section 0d** (project/canvas/asset schema and domains, repositories, hardened archive reader/writer, legacy import with idempotency and rollback, ordinary backup v1, project and upload bindings, the canvas persistence adapter, the migration UI and the free-canvas regression suite). WP-01, WP-02 and WP-03 remain COMPLETE for their recorded scopes.",
);

// Section 0d, in the same shape the earlier packages used.
const section = [
    "",
    "---",
    "",
    "# 0d. WP-04 result (2026-09-17)",
    "",
    "## Scope completed",
    "",
    "- **Status: COMPLETE (WP-04 scope)**. Every acceptance item below was executed on this host; the",
    "  limitations are listed explicitly and are not disguised as passes.",
    "- Schema: forward-only `000004_projects_canvas.sql` adds workspaces, projects, canvas documents,",
    "  nodes, edges, chat sessions, assets, asset versions, asset files, archived generation history",
    "  and the legacy import bookkeeping. `000005_legacy_project_fingerprints.sql` adds the per-project",
    "  fingerprint table the idempotency check needs. `000001`-`000003` were not modified.",
    "- Domain: `internal/domain/project` (workspaces, projects, canvas kinds, the relation registry",
    "  with the `generic` fallback) and `internal/domain/asset` (assets, versions, the approval",
    "  preconditions). Neither mints or validates an identifier (ADR-0005).",
    "- Application: `internal/application/projects` (commands and queries), `.../assets`,",
    "  `.../legacy` (snapshot, fingerprint, transform, import) and `.../backup` (export and restore).",
    "- Infrastructure: SQLite repositories with revision guards and cascades, the atomic import, the",
    "  hardened ZIP reader/writer, and the backup store.",
    "- Bindings: `ProjectsBinding` (projects, canvas, nodes, edges, chats, import),",
    "  `LegacyUploadBinding` (the chunked base64 channel), `BackupBinding` (export and restore preview).",
    "  The upload surface was audited down to its five transfer methods: the configuration entry point",
    "  and the media reader are package-level functions, so neither a filesystem path nor an internal",
    "  port reaches the webview.",
    "- Frontend: the canvas persistence adapter (Go and legacy implementations with one mode decision),",
    "  the migration dialog with both locales, and a Playwright regression for the free canvas.",
    "",
    "## Commands executed and actual results",
    "",
    "| Command | Result |",
    "|---|---|",
    "| `go test ./... -count=1` | **PASS** (19 packages ok) |",
    "| `go vet ./...` | **PASS** |",
    "| `gofmt -l .` | **PASS** (no output) |",
    "| `node scripts/security-scan.mjs` | **PASS** (296 files scanned; 1 audited dynamic-execution exception, 4 audited legacy direct-call files with named owners) |",
    "| `web`: `npm run typecheck` | **PASS** |",
    "| `web`: `npm test` | **PASS** (34 tests) |",
    "| `web`: `npm run test:e2e` | **PASS** (13 passed, 1 skipped; the skip is the crop dialog, which needs node content a headless run cannot supply) |",
    "| `web`: `npm run build` | **PASS** with the pre-existing >500 kB chunk warning |",
    "| `scripts/verify.sh` / `scripts/verify.ps1` | **PASS**; both now run the canvas regression, and each reports its own skip reason when Playwright is absent |",
    "| `wails build -s` (v2.15.0) | **PASS**; produced `build/bin/InfiniteAtelier.exe` |",
    "| `git diff --check` | **PASS** (exit 0; only pre-existing LF/CRLF advisory warnings) |",
    "| `go test -race ./... -count=1` | **ENVIRONMENT FAILURE, not a pass** — the host 32-bit MinGW GCC cannot compile amd64 CGO. |",
    "",
    "## Acceptance",
    "",
    "| ID | Result | Evidence |",
    "|---|---|---|",
    "| AC-LEGACY-001 | **PASS** | `TestImportAllNodeTypesIsComplete` (counts, text, viewport, warnings, relations), `TestLegacyImportSnapshotIsAtomic` (the real store), `TestImportMissingMediaIsReportedNotFatal`, `TestImportMalformedMetadataIsRetained`, and `TestMockPayloadsPassTheRealAllowlist`-style media checks against the real fixtures in `testdata/old-projects/`. |",
    "| AC-LEGACY-002 | **PASS** | `TestImportIsIdempotent` (second import skips, copy mode makes a distinct project, media deduplicated) plus `TestLegacyProjectFingerprintIsPerProject` against the real store, which is the level the earlier revision failed at. |",
    "| AC-LEGACY-003 | **PASS** | `TestLegacyImportRollsBackCompletely` (one bundle malformed, nothing written), `TestLegacyProjectFingerprintSurvivesFailure`, `TestImportFailureLeavesNoProject` (the stage is named), `TestImportDatabaseFailureIsReported`; the abandoned-upload tests cover temporary-file cleanup. |",
    "| AC-CANVAS-004 | **PASS** | `web/e2e/canvas-regression.spec.ts`: add, move (asserting a second node did not shift), delete, multi-select, box select, zoom, pan (asserting every node shifted by one delta), undo/redo, connections, the minimap toggle, the generation prompt surface, the image node's actions and a reload. Each was mutation-checked: breaking the behaviour fails the test. |",
    "| AC-BACKUP-001 | **PASS** | `TestBackupRoundTrip`, `TestBackupContainsNoSecrets`, `TestRestoreRefusesSecretBearingArchive`, `TestRestoreRefusesCredentialHiddenInAnObject`, `TestBackupScanCoversAuthorizationAndCookie`, `TestRestoreRefusesTamperedArchive`, `TestBackupExportAgainstRealStorage`. |",
    "| AC-BACKUP-002 (partial) | **PARTIAL** | Tamper detection and staged validation are tested; the atomic *swap* of a live database is not implemented, so a restore validates and stages but the promotion step belongs to WP-12. |",
    "| AC-SEC-002 | **PASS** | The archive corpus in `internal/infrastructure/archive/archive_test.go`: `../`, absolute paths, drive letters, UNC, device names, trailing dot/space, dot elements, symlinks, duplicate normalised paths, entry-count and ratio bombs, size ceilings, corrupt input, a false manifest and a wrong hash. |",
    "",
    "## Independent review",
    "",
    "**Spec review (independent subagent): CHANGES REQUIRED → fixed.** It found six blockers, all confirmed",
    "against the code and fixed:",
    "",
    "- A node the canvas created was never stored: the binding treated an empty id as \"create\" while the",
    "  adapter always sends the id it minted, so every new node took the update path and failed. The",
    "  binding now decides by whether the row exists.",
    "- The viewport was never persisted: the adapter sent revision 0 against a document whose revision",
    "  starts at 1. The service now writes against the revision it just read.",
    "- Idempotency could never fire: the store compared per-project fingerprints, but the import recorded",
    "  the run's fingerprint, so a second import duplicated the project. A new table holds one row per",
    "  imported project, and `TestLegacyProjectFingerprintIsPerProject` pins it against the real store —",
    "  the in-memory double had been recording wh
