import io

p = "scripts/gen-canary-fixture.mjs"
s = io.open(p, encoding="utf-8").read()

# 1. The builders, inserted before main().
anchor = "function main() {"
builders = '''// buildApprovedFacts writes the facts and rules a user approved.
//
// Section 18.1's "\u5df2\u6279\u51c6\u4e8b\u5b9e" is the layer a stage's prompt carries, so the fixture states them
// in the shape the rule list uses: a category, the fact itself, and the STRENGTH a user gave it.
// The approved ones are the only ones here \u2014 a candidate a user has not accepted is not a fact, which
// is the distinction the tool `story.read_rules` exists to keep.
function buildApprovedFacts() {
    const facts = [
        { category: "world", text: "\u6c5f\u6c34\u6bcf\u5e74\u5165\u79cb\u6da8\u4e00\u6b21\uff0c\u6e21\u8239\u5728\u6da8\u6c34\u671f\u505c\u8fd0\u3002", strength: "hard" },
        { category: "world", text: "\u94dc\u724c\u662f\u6e21\u53e3\u8239\u5de5\u7684\u51ed\u8bc1\uff0c\u4e00\u4eba\u4e00\u724c\uff0c\u4e0d\u5f97\u8f6c\u501f\u3002", strength: "hard" },
        { category: "world", text: "\u53bf\u8859\u7684\u6863\u6848\u5728\u5341\u5e74\u524d\u7684\u4e00\u573a\u706b\u91cc\u70e7\u4e86\u4e00\u534a\u3002", "strength": "soft" },
        { category: "character", text: "\u767d\u638c\u67dc\u77e5\u9053\u90a3\u4e2a\u540d\u5b57\uff0c\u4f46\u4ed6\u4e0d\u80af\u8bf4\u3002", strength: "hard" },
        { category: "character", text: "\u6c88\u781a\u5728\u627e\u4e00\u4e2a\u5341\u5e74\u524d\u6d88\u5931\u7684\u4eba\u3002", strength: "hard" },
        { category: "character", text: "\u8001\u5468\u5bf9\u6e21\u53e3\u7684\u6bcf\u4e00\u6761\u8239\u90fd\u719f\uff0c\u4f46\u4ece\u4e0d\u63d0\u5341\u5e74\u524d\u3002", strength: "soft" },
        { category: "plot", text: "\u7ed3\u5c3e\u5fc5\u987b\u7559\u4e0b\u4e00\u4e2a\u672a\u89e3\u7684\u7591\u95ee\uff0c\u4e0d\u5f97\u6536\u675f\u3002", strength: "hard" },
        { category: "plot", text: "\u524d\u4e09\u5206\u949f\u5185\u5fc5\u987b\u51fa\u73b0\u90a3\u4e2a\u540d\u5b57\u3002", strength: "hard" },
    ];
    return {
        note: "Generated by scripts/gen-canary-fixture.mjs. Do not edit by hand.",
        approvedBy: "user-1",
        facts,
    };
}

// buildExpectedSkeleton writes the key points a story skeleton is expected to contain.
//
// Section 18.1's "\u671f\u671b\u6545\u4e8b\u9aa8\u67b6\u5173\u952e\u70b9" is what a supervisor's findings are judged
// against in a canary, so the fixture states the SHAPE a skeleton must have rather than a
// particular version's text: the hooks, the conflict, and which of the approved facts
// each one has to be consistent with. A fixture that pinned the text would fail on any
// change to a skill, which is not what the skeleton stage's quality is about.
function buildExpectedSkeleton() {
    return {
        note: "Generated by scripts/gen-canary-fixture.mjs. Do not edit by hand.",
        requiredFields: ["openingHook", "coreConflict", "turningPointsJson", "climax", "endingHook"],
        mustMention: ["\u6c88\u781a", "\u767d\u638c\u67dc"],
        // The ending hook has to leave a question open, which is the approved plot rule.
        endingHookMustLeaveOpenQuestion: true,
        openingHookMustAppearWithinSeconds: 180,
        // The facts a skeleton is checked against, by their text, so a canary can assert the
        // relationship rather than a substring the generator happened to write.
        consistentWith: [
            "\u6c88\u781a\u5728\u627e\u4e00\u4e2a\u5341\u5e74\u524d\u6d88\u5931\u7684\u4eba\u3002",
            "\u767d\u638c\u67dc\u77e5\u9053\u90a3\u4e2a\u540d\u5b57\uff0c\u4f46\u4ed6\u4e0d\u80af\u8bf4\u3002",
            "\u7ed3\u5c3e\u5fc5\u987b\u7559\u4e0b\u4e00\u4e2a\u672a\u89e3\u7684\u7591\u95ee\uff0c\u4e0d\u5f97\u6536\u675f\u3002",
        ],
    };
}

// buildBadScript writes a DELIBERATELY WRONG script document.
//
// Section 18.1's "\u6545\u610f\u9519\u8bef\u5267\u672c". Each fault is one a validator or a supervisor
// must catch, and every one is stated with the rule it breaks so a test can assert which
// failure it observed rather than only that something failed. The faults are chosen from
// the checks this build actually makes:
//
//   - a scene ordinal that REPEATS, which `ScriptStructure.Validate` refuses;
//   - a line whose `sceneId` names a scene it is not nested under, which the same validator
//     refuses because the nesting IS the relation;
//   - a `sourceStoryEventId` that does not exist, which the service's reference check refuses
//     because the schema has no foreign key for it;
//   - an `interiorExterior` value outside the closed vocabulary, which SQL's CHECK refuses;
//   - a duration on the SCENE that is negative, which the column's CHECK refuses.
//
// A document with one fault would be a test of one check; this one is a document that no
// single check can accept, and the faults are ordered from the outermost to the innermost so
// a reader can see which one a given validator reports first.
function buildBadScript() {
    return {
        note: "Generated by scripts/gen-canary-fixture.mjs. Do not edit by hand. This document is WRONG on purpose: it is the fixture AGENT_CONTRACTS section 18.1 asks for (\u6545\u610f\u9519\u8bef\u5267\u672c), and every fault names the rule it breaks.",
        faults: [
            { field: "scenes[1].ordinal", value: 1, rule: "ordinals must run from one with no gap and no repeat" },
            { field: "scenes[0].dialogueLines[0].sceneId", value: "scene-not-the-parent", rule: "a line must name the scene it is nested under" },
            { field: "scenes[0].sourceStoryEventId", value: "event-that-does-not-exist", rule: "a scene's source event must exist in this project" },
            { field: "scenes[0].interiorExterior", value: "INSIDE", rule: "the interior/exterior marking is a closed vocabulary" },
            { field: "scenes[1].estimatedDurationSeconds", value: -30, rule: "an estimated duration cannot be negative" },
        ],
        script: {
            scenes: [
                {
                    ordinal: 1,
                    sceneNumber: "1",
                    slugline: "INT. \u6e21\u53e3 - \u65e5",
                    interiorExterior: "INSIDE",
                    summary: "\u4e00\u4e2a\u573a\u666f\uff0c\u5b83\u7684\u5377\u6807\u8bb0\u4e0d\u5c5e\u4e8e\u4efb\u4f55\u5408\u6cd5\u53d6\u503c\u3002",
                    estimatedDurationSeconds: 90,
                    sourceStoryEventId: "event-that-does-not-exist",
                    dialogueLines: [
                        { ordinal: 1, sceneId: "scene-not-the-parent", type: "dialogue", text: "\u8fd9\u53e5\u8bdd\u6302\u5728\u9519\u7684\u573a\u666f\u4e0b\u3002" },
                    ],
                    shots: [],
                },
                {
                    verbose_note: "This scene repeats ordinal 1, and asserts a negative duration.",
                    ordinal: 1,
                    sceneNumber: "2",
                    slugline: "EXT. \u6e21\u53e3 - \u591c",
                    interiorExterior: "EXT",
                    summary: "\u7b2c\u4e8c\u4e2a\u573a\u666f\u91cd\u590d\u4e86\u7b2c\u4e00\u4e2a\u7684\u5e8f\u53f7\u3002",
                    estimatedDurationSeconds: -30,
                    dialogueLines: [],
                    shots: [],
                },
            ],
        },
    };
}

'''
assert anchor in s, "main"
s = s.replace(anchor, builders + anchor, 1)

# 2. main() writes and checks the three.
old = '''    if (check) {
        const currentSource = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
        const currentExpected = existsSync(expectedPath) ? readFileSync(expectedPath, "utf8") : "";
        if (currentSource !== text || currentExpected !== JSON.stringify(expected, null, 2) + "\\n") {
            console.error("FAIL: the committed fixture differs from what the generator produces");
            process.exit(1);
        }
        console.log(`PASS: fixture is current (${totalChars} Chinese characters, ${chapterMeta.length} chapters)`);
        return;
    }
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, text, "utf8");
    writeFileSync(expectedPath, JSON.stringify(expected, null, 2) + "\\n", "utf8");
    console.log(`wrote ${outPath}`);
    console.log(`wrote ${expectedPath}`);
    console.log(`${totalChars} Chinese characters, ${chapterMeta.length} chapters`);
}'''
new = '''    // Section 18.1's three WP-08 fixtures, serialised the same way as the two above so a
    // `--check` run compares bytes rather than objects.
    const wp08 = [
        [approvedFactsPath, JSON.stringify(buildApprovedFacts(), null, 2) + "\\n", "approved facts"],
        [expectedSkeletonPath, JSON.stringify(buildExpectedSkeleton(), null, 2) + "\\n", "expected story skeleton"],
        [badScriptPath, JSON.stringify(buildBadScript(), null, 2) + "\\n", "deliberately wrong script"],
    ];
    if (check) {
        const currentSource = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
        const currentExpected = existsSync(expectedPath) ? readFileSync(expectedPath, "utf8") : "";
        let drifted = currentSource !== text || currentExpected !== JSON.stringify(expected, null, 2) + "\\n";
        for (const [path, body, label] of wp08) {
            const current = existsSync(path) ? readFileSync(path, "utf8") : "";
            if (current !== body) {
                console.error(`FAIL: the ${label} fixture differs from what the generator produces`);
                drifted = true;
            }
        }
        if (drifted) {
            process.exit(1);
        }
        console.log(`PASS: fixtures are current (${totalChars} Chinese characters, ${chapterMeta.length} chapters, ${wp08.length} WP-08 fixtures)`);
        return;
    }
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, text, "utf8");
    writeFileSync(expectedPath, JSON.stringify(expected, null, 2) + "\\n", "utf8");
    console.log(`wrote ${outPath}`);
    console.log(`wrote ${expectedPath}`);
    for (const [path, body] of wp08) {
        writeFileSync(path, body, "utf8");
        console.log(`wrote ${path}`);
    }
    console.log(`${totalChars} Chinese characters, ${chapterMeta.length} chapters`);
}'''
assert old in s, "main body"
s = s.replace(old, new, 1)

io.open(p, "w", encoding="utf-8", newline="\n").write(s)
print("generator patched")
