import io

p = 'scripts/gen-canary-fixture.mjs'
s = io.open(p, encoding='utf-8').read()

# 1. The two paths.
old_paths = '''const badScriptPath = join(repoRoot, "testdata", "canary-drama", "bad-script.json");'''
new_paths = '''const badScriptPath = join(repoRoot, "testdata", "canary-drama", "bad-script.json");
const badStoryboardPath = join(repoRoot, "testdata", "canary-drama", "bad-storyboard.json");
const expectedStoryboardPath = join(repoRoot, "testdata", "canary-drama", "expected-storyboard.json");'''
assert old_paths in s, "paths anchor"
s = s.replace(old_paths, new_paths, 1)

# 2. The builders, before main().
old_main = '''function main() {'''
new_main = '''/**
 * The storyboard fixtures, which are AC-BOARD-002's subject.
 *
 * The criterion is a board whose SIXTH shot wears the wrong costume: a supervisor has to
 * locate it at that shot, the evidence has to point at two versions, and a FIX has to
 * change only that row. So the fixture states a board where every other row is consistent
 * and the sixth contradicts the plan's continuity rule — and `bad-storyboard.json` names
 * each fault with the rule it breaks, the same way `bad-script.json` does.
 *
 * The shot count is twelve, because AC-BOARD-001 asks for at least twelve shots and a
 * fixture with fewer would pass a board the criterion would reject.
 */
const STORYBOARD_SHOT_COUNT = 12;
/** The row the criterion names, one-based. */
const STORYBOARD_BAD_SHOT = 6;

/** storyboardRow builds one consistent row. */
function storyboardRow(ordinal, coat) {
    const number = String(ordinal);
    return {
        ordinal,
        shotId: `shot-${number}`,
        shotSize: ordinal === STORYBOARD_SHOT_COUNT ? "WS" : "MS",
        cameraAngle: ordinal === STORYBOARD_BAD_SHOT ? "high angle" : "eye level",
        cameraMovement: ordinal === STORYBOARD_BAD_SHOT ? "slow push in" : "static",
        durationSeconds: 4,
        visualDescription: `第 ${number} 个镜头：渡口的煤灯下，沈砚停步。`,
        actionDescription: `沈砚在第 ${number} 个镜头里侧身让开一步。`,
        dialogueAudioSummary: ordinal === 1 ? "沈砚：灯还亮着。" : "",
        // The continuity rule the plan fixes and every row but one respects.
        continuityNotes: `沈砚穿的是${coat}。`,
        firstFrameDescription: `第 ${number} 个镜头的首帧：煤灯在画面左侧。`,
        lastFrameDescription: `第 ${number} 个镜头的尾帧：煤灯移到画面右侧。`,
        videoMotionDescription: "镜头轻微横移，人物几乎不动。",
        assetRefs: [{ assetId: "asset-shen-yan", usageRole: "costume" }],
    };
}

function buildBadStoryboard() {
    const rows = [];
    for (let ordinal = 1; ordinal <= STORYBOARD_SHOT_COUNT; ordinal += 1) {
        // The plan fixes the winter coat from shot one. The sixth row wears the summer one
        // — AFTER the scene that changes it, which is the fault the criterion describes.
        const coat = ordinal === STORYBOARD_BAD_SHOT ? "夏装" : "冬装";
        rows.push(storyboardRow(ordinal, coat));
    }
    return {
        note: "Generated by scripts/gen-canary-fixture.mjs. Do not edit by hand. This document is WRONG on purpose: it is the fixture AGENT_CONTRACTS section 18.1 asks for (故意错误分镜), and every fault names the rule it breaks.",
        faults: [
            {
                field: `items[${STORYBOARD_BAD_SHOT - 1}].continuityNotes`,
                value: "夏装",
                rule: "a character's costume must hold across the rows a continuity rule fixes",
                locatedAtShot: `shot-${STORYBOARD_BAD_SHOT}`,
            },
        ],
        mustLocateAt: `shot-${STORYBOARD_BAD_SHOT}`,
        storyboard: {
            versionNumber: 1,
            items: rows,
        },
    };
}

function buildExpectedStoryboard() {
    const rows = [];
    for (let ordinal = 1; ordinal <= STORYBOARD_SHOT_COUNT; ordinal += 1) {
        // Every row wears the winter coat, including the sixth: the FIX changes THAT row
        // and nothing else.
        rows.push(storyboardRow(ordinal, "冬装"));
    }
    return {
        note: "Generated by scripts/gen-canary-fixture.mjs. Do not edit by hand.",
        shotCount: STORYBOARD_SHOT_COUNT,
        requiredFields: [
            "shotId",
            "shotSize",
            "cameraAngle",
            "cameraMovement",
            "durationSeconds",
            "visualDescription",
            "actionDescription",
            "dialogueAudioSummary",
            "continuityNotes",
            "firstFrameDescription",
            "lastFrameDescription",
            "videoMotionDescription",
        ],
        // The three migration 000018 added, called out because they are what WP-09 had
        // nowhere to store: a reader checking FR-070 wants to know they are asserted.
        fr070Fields: ["firstFrameDescription", "lastFrameDescription", "videoMotionDescription"],
        continuityRule: "沈砚从镜头一到结尾都穿冬装。",
        totalDurationSeconds: STORYBOARD_SHOT_COUNT * 4,
        orderIsTheArrayOrder: true,
        storyboard: {
            versionNumber: 1,
            items: rows,
        },
    };
}

function main() {'''
assert old_main in s, "main anchor"
s = s.replace(old_main, new_main, 1)

# 3. The writes and the check.
old_wp08 = '''        [badScriptPath, JSON.stringify(buildBadScript(), null, 2) + "\\n", "deliberately wrong script"],
    ];'''
new_wp08 = '''        [badScriptPath, JSON.stringify(buildBadScript(), null, 2) + "\\n", "deliberately wrong script"],
        [badStoryboardPath, JSON.stringify(buildBadStoryboard(), null, 2) + "\\n", "deliberately wrong storyboard"],
        [expectedStoryboardPath, JSON.stringify(buildExpectedStoryboard(), null, 2) + "\\n", "expected storyboard"],
    ];'''
assert old_wp08 in s, "wp08 anchor"
s = s.replace(old_wp08, new_wp08, 1)
s = s.replace('${wp08.length} WP-08 fixtures', '${wp08.length} fixtures')

io.open(p, 'w', encoding='utf-8').write(s)
print("generator extended")
