// Package agenttools builds the built-in tool table of AGENT_CONTRACTS section 6.
//
// It is a package of its own rather than code inside agentruntime because of the
// dependency direction (AGENTS section 7.2). The runtime is application code that
// knows about agents, prompts and schemas; each tool's handler calls a DIFFERENT
// application service — story, script, storyboard, workflow, memory, assets — and
// putting those calls inside the runtime would make the runtime depend on every
// service in the build. Here the dependency points one way: this package imports the
// runtime and the services, and the runtime imports neither.
//
// # Every tool has a real path
//
// AGENTS section 12 forbids "只创建接口无真实路径", and section 6.1 gives a tool a
// Handler for exactly that reason. So every entry in the table calls an application
// service that owns the write and enforces the domain's rules — never a direct SQL
// statement, never a placeholder, never a fixed document.
//
// # Two of section 6.2's example tools are deliberately NOT in the table
//
// The section's example list includes `story.create_event_candidates` and
// `workflow.request_user_gate`'s sibling controls. Two of its names have no honest
// implementation in this build, and they are absent rather than stubbed:
//
//   - `story.create_event_candidates`. The event-extraction stage's write path is the
//     EXTRACTION SERVICE, and WP-06 built its seam for the runtime to plug into: the
//     runtime implements that package's Extractor port and the service does the
//     validating and the writing (see drama_wiring.go). A tool doing the same thing
//     would be a second write path for one stage, and the two would disagree about
//     which rows are candidates. The stage's agent therefore calls the extraction
//     service through the runtime, not through a tool.
//   - `provider.submit_image_job`. Media generation is a Job, not an agent tool: the
//     specification says so outright ("媒体生成本身由 Job/Provider Service 执行，不让 LLM
//     阻塞等待大文件", section 19), and WP-11 owns it. A tool here would block a prompt
//     on a file download.
//
// Both are recorded in ADR-0011 rather than left as a silent gap.
//
// # Arguments are validated before a handler sees them
//
// Section 6.1's chain is "JSON parse → Schema validation → Tool ACL → scope
// validation → execute". The schemas live in schemas/agent/tools/ and are generated by
// scripts/gen-tool-schemas.mjs from the same key list this package registers, with a
// test comparing the two. A handler therefore decodes a shape it can trust and still
// checks every VALUE it uses, because a schema constrains a shape and not a referent.
package agenttools

import (
	"context"
	"encoding/json"
	"strings"

	agentruntime "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/agentruntime"
	appassets "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/assets"
	appextraction "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/extraction"
	appmemory "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/memory"
	appprojects "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/projects"
	appscript "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/script"
	appstory "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/story"
	appstoryboard "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/storyboard"
	appworkflow "github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/application/workflow"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/agent"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/asset"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/story"
	"github.com/newyngwieslash-ops/infinite-atelier-mine-0903/internal/domain/versioning"
)

// createdByAgent is the attribution every write tool records.
//
// DOMAIN_MODEL section 13.4 distinguishes a version a person made from one an agent
// made, and PRD FR-100's audit is what that distinction is for: a reviewer has to be
// able to tell which versions came from an agent.
const createdByAgent = versioning.CreatedByAgent

// ChapterReader is the chapter-text read the story tools use.
//
// It is extraction.ChapterReader, declared here as an interface rather than imported
// as the concrete desktop adapter, because the adapter lives in the desktop layer and
// this package must not: the composition root passes whatever satisfies it. The port
// is the one WP-06 declared for the same walk — chapter → version → document — and
// reusing it means there is ONE implementation of "what text is this chapter", not
// two that could disagree about the rune slicing.
type ChapterReader interface {
	ChapterWithText(ctx context.Context, chapterID string) (appextraction.ChapterText, error)
}

// Deps are the services the tools call.
//
// One struct rather than eight parameters. No field is optional in the sense of
// "silently absent": Build refuses a table whose tools name a service that is not
// there, so a build that forgot one gets a startup refusal naming the service rather
// than a tool that fails at run time — the fail-closed direction AGENTS section 4.3
// asks for.
type Deps struct {
	Story      *appstory.Service
	Script     *appscript.Service
	Storyboard *appstoryboard.Service
	Workflow   *appworkflow.Service
	Memory     *appmemory.Service
	Assets     *appassets.Service
	// Gaps serves the asset gap report. It is a service of the ASSETS package but a
	// separate one, because a report is a different aggregate from an asset and a build
	// that has no episode or script store composes the assets service without it.
	Gaps     *appassets.GapService
	Projects *appprojects.Service
	// Chapters reads a chapter's text. It is a port rather than a service because the
	// adapter that implements it lives in the desktop layer.
	Chapters ChapterReader
}

// Available reports whether every service a tool needs is composed.
func (d Deps) Available() bool {
	return d.Story != nil && d.Script != nil && d.Storyboard != nil &&
		d.Workflow != nil && d.Memory != nil && d.Assets != nil &&
		d.Gaps != nil && d.Projects != nil && d.Chapters != nil
}

// Keys lists every tool key this package registers.
//
// It is exported so a test can compare it against schemas/agent/tools/KEYS.txt: a tool
// registered without a schema is refused by NewTools, but a SCHEMA without a
// registration would otherwise be invisible, and this is what makes that visible too.
func Keys() []string {
	keys := make([]string, 0, len(table))
	for _, entry := range table {
		keys = append(keys, entry.key)
	}
	return keys
}

// tableEntry is one tool's registration, before the services are bound.
type tableEntry struct {
	key     string
	mode    agent.ToolMode
	scope   string
	maxByte int
	// build receives the services and returns the handler. A function rather than a
	// method value so the table can be a package-level literal: the services arrive at
	// Build, not at init.
	build func(Deps) agentruntime.ToolHandler
}

// table is the whole tool set, in the order the schema generator lists it.
//
// A tool is registered here ONCE and its schema path is derived from its key, so a
// rename cannot leave a schema behind.
var table = []tableEntry{
	// --- Workflow ---
	{"workflow.read_state", agent.ToolRead, "project", 64 * 1024, bindReadState},
	{"workflow.request_user_gate", agent.ToolControl, "project", 4 * 1024, bindRequestUserGate},

	// --- Story reads ---
	{"story.read_events", agent.ToolRead, "project", 128 * 1024, bindReadEvents},
	{"story.read_chapter_text", agent.ToolRead, "project", 256 * 1024, bindReadChapterText},
	{"story.read_rules", agent.ToolRead, "project", 64 * 1024, bindReadRules},

	// --- Script reads ---
	{"script.read_story_skeleton", agent.ToolRead, "project", 128 * 1024, bindReadStorySkeleton},
	{"script.read_adaptation_strategy", agent.ToolRead, "project", 128 * 1024, bindReadAdaptationStrategy},
	{"script.read_script_version", agent.ToolRead, "project", 256 * 1024, bindReadScriptVersion},
	// The structure is its own read with its own bound, and it is larger than the version row: a
	// hundred scenes of dialogue and shots is the artifact itself, while the row is a summary of it.
	{"script.read_script_structure", agent.ToolRead, "project", 256 * 1024, bindReadScriptStructure},

	// --- Script writes ---
	{"script.create_story_skeleton_version", agent.ToolWrite, "project", 16 * 1024, bindCreateStorySkeletonVersion},
	{"script.create_adaptation_strategy_version", agent.ToolWrite, "project", 16 * 1024, bindCreateAdaptationStrategyVersion},
	{"script.create_script_version", agent.ToolWrite, "project", 16 * 1024, bindCreateScriptVersion},
	// The whole version's content in one call, and NO DURATION FIELD: §17 puts ID, order, uniqueness
	// and 时长求和 in the code's column, so this tool states a shape and the service derives the rest.
	// The bound is the output's; the INPUT is bounded by its schema, which is where a model's scene
	// count is refused rather than truncated.
	// The shots, which are what a storyboard's rows are one per. The schema's storyboard
	// stage had only `script.read_script_version` — a summary that answers "how many
	// scenes" — so an agent asked to board a script could not see the shots it was
	// boarding and would have had to invent them.
	//
	// It sits here rather than beside the other reads because the schema generator's table
	// is the ORDER OF RECORD: `TestEverySchemaHasARegisteredTool` compares this list with
	// KEYS.txt element by element, which is what makes a rename or a reorder visible
	// rather than merely a difference.
	{"script.read_shots", agent.ToolRead, "project", 256 * 1024, bindReadShots},
	{"script.create_script_structure", agent.ToolWrite, "project", 16 * 1024, bindCreateScriptStructure},

	// --- Storyboard reads ---
	{"storyboard.read_director_plan", agent.ToolRead, "project", 128 * 1024, bindReadDirectorPlan},
	{"storyboard.read_storyboard", agent.ToolRead, "project", 256 * 1024, bindReadStoryboard},

	// --- Storyboard writes ---
	{"storyboard.create_director_plan_version", agent.ToolWrite, "project", 16 * 1024, bindCreateDirectorPlanVersion},
	{"storyboard.create_storyboard_version", agent.ToolWrite, "project", 16 * 1024, bindCreateStoryboardVersion},
	{"storyboard.create_storyboard_panel_version", agent.ToolWrite, "project", 16 * 1024, bindCreatePanelVersion},

	// --- Assets ---
	{"asset.read_approved_assets", agent.ToolRead, "project", 128 * 1024, bindReadApprovedAssets},
	// The gap report's write and read. Section 10.1 gives asset_analysis a required user
	// gate and a supervisor of NONE, so the model WRITES the analysis and a person
	// approves it — which is why the write tool creates a draft and cannot approve.
	{"asset.create_gap_report", agent.ToolWrite, "project", 16 * 1024, bindCreateGapReport},
	{"asset.read_gap_report", agent.ToolRead, "project", 128 * 1024, bindReadGapReport},
	{"asset.create_candidate_version", agent.ToolWrite, "project", 16 * 1024, bindCreateCandidateVersion},

	// --- Memory ---
	//
	// READ rather than a mode of its own: a recall reads stored messages and writes
	// nothing. Section 6.2 spells it `memory.deep_recall`, and this build implements the
	// RECENT window WP-07's scope item 15 allows; the name keeps the section's spelling
	// so a skill does not change when WP-10 deepens it.
	{"memory.deep_recall", agent.ToolRead, "project", 64 * 1024, bindDeepRecall},
}

// Build assembles the table.
func Build(deps Deps) (*agentruntime.Tools, error) {
	if !deps.Available() {
		return nil, agent.InvalidError(buildRefusal(deps))
	}
	tools := make([]agentruntime.Tool, 0, len(table))
	for _, entry := range table {
		tools = append(tools, agentruntime.Tool{
			Spec: agent.ToolSpec{
				Key: entry.key, Mode: entry.mode, Scope: entry.scope,
				MaxOutputBytes: entry.maxByte,
			},
			Handler:    entry.build(deps),
			SchemaPath: "schemas/agent/tools/" + entry.key + ".json",
		})
	}
	return agentruntime.NewTools(tools)
}

// buildRefusal names the first missing service.
//
// It names the service rather than saying "a tool is invalid", because the caller's
// next step is to look at the composition root and the name is what tells them which
// line to read.
func buildRefusal(deps Deps) string {
	switch {
	case deps.Story == nil:
		return "The story service is not composed, so its tools cannot be registered."
	case deps.Script == nil:
		return "The script service is not composed, so its tools cannot be registered."
	case deps.Storyboard == nil:
		return "The storyboard service is not composed, so its tools cannot be registered."
	case deps.Workflow == nil:
		return "The workflow service is not composed, so its tools cannot be registered."
	case deps.Memory == nil:
		return "The memory service is not composed, so its tools cannot be registered."
	case deps.Assets == nil:
		return "The asset service is not composed, so its tools cannot be registered."
	case deps.Projects == nil:
		return "The projects service is not composed, so its tools cannot be registered."
	case deps.Chapters == nil:
		return "No chapter reader is composed, so the story text tool cannot be registered."
	default:
		return "A service a tool needs is not composed."
	}
}

// decodeArguments reads a handler's arguments.
//
// An empty argument object is legal — a tool whose inputs all have defaults takes none
// — and anything that fails to decode is refused. Unknown fields are refused rather
// than ignored, because the runtime validated these arguments against the tool's
// schema: a field the schema does not describe means the validation and this handler
// disagree about the contract, and silently ignoring it would hide that.
func decodeArguments(raw json.RawMessage, target any) error {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" || trimmed == "{}" || trimmed == "null" {
		return nil
	}
	decoder := json.NewDecoder(strings.NewReader(trimmed))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return agent.InvalidError("The tool's arguments could not be read.")
	}
	return nil
}

// required reads a required identifier argument.
//
// It refuses rather than defaulting, and the message names the field: a tool that
// silently used an empty identifier would read no row, and the failure would surface as
// an empty result rather than as a bad request.
func required(value, field string) (string, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return "", agent.InvalidError("The tool needs a " + field + ".")
	}
	return trimmed, nil
}

// limitOf clamps a caller's page size.
//
// A model asking for a million rows gets the ceiling rather than an error, because the
// request is well formed and the bound is the runtime's; a model asking for zero gets
// the fallback, because zero is what an omitted field decodes to.
func limitOf(requested, fallback, ceiling int) int {
	if requested <= 0 {
		return fallback
	}
	if requested > ceiling {
		return ceiling
	}
	return requested
}

// agentActor is the created-by attribution every write tool records.
//
// The identifier is the AGENT RUN rather than the stage, and the distinction is what
// DOMAIN_MODEL section 13.4 is for: a version's created-by names WHO produced it, and a
// stage is the workflow position where it happened. A run that was superseded and re-run in
// the same stage is a different author, which is exactly the fact a reviewer needs to see.
func agentActor(request agentruntime.ToolRequest) (versioning.CreatedByType, string) {
	return createdByAgent, request.AgentRunID
}

// storyStatusFilter reads an optional status filter argument.
//
// An unknown status is refused rather than passed through: story.FactStatus has a
// closed vocabulary, and a query for a status that does not exist would return an empty
// list — which reads as "this project has no such facts" rather than as a bad request.
func storyStatusFilter(value string) (story.FactStatus, error) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return "", nil
	}
	status := story.FactStatus(trimmed)
	if !story.IsValidFactStatus(status) {
		return "", agent.InvalidError("That fact status is not recognised.")
	}
	return status, nil
}

// assetTypes reads an optional type filter.
func assetTypes(values []string) ([]asset.Type, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]asset.Type, 0, len(values))
	for _, value := range values {
		trimmed := asset.Type(strings.TrimSpace(value))
		if !asset.IsValidType(trimmed) {
			return nil, agent.InvalidError("That asset type is not recognised.")
		}
		out = append(out, trimmed)
	}
	return out, nil
}

// contextDone reports whether the caller's context has finished.
//
// Every handler checks it before calling a service, because section 15's "Runtime 停止
// 流和后续 Tool" is a property of the tool layer as much as of the runner: the runner
// refuses the NEXT call, but it cannot recall one already running, so the handler is
// what stops it.
func contextDone(ctx context.Context) error {
	if err := ctx.Err(); err != nil {
		return &agentruntime.CancelledError{Cause: err}
	}
	return nil
}

// itoaSmall renders a small non-negative integer without importing strconv for a few
// call sites, so the reason is visible where it is used.
func itoaSmall(value int) string {
	if value <= 0 {
		return "0"
	}
	digits := ""
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	return digits
}
